from collections.abc import Buffer as _BufferProtocol
from typing import Any, overload

# --- Constants ---
from .constants import *

# --- Module Level Functions ---

def enable_debug() -> None: ...
def context() -> dict[str, Any]: ...
def clear(mask: int) -> None: ...
def clear_color(r: float, g: float, b: float, a: float) -> None: ...
def viewport(x: int, y: int, width: int, height: int) -> None: ...
def bind_default_framebuffer() -> None: ...
def get_active_context() -> Context | None: ...
def memory_barrier(mask: int) -> None: ...

@overload
def inspect(obj: Buffer) -> dict[str, int | bool | str]: 
    ...

@overload
def inspect(obj: Pipeline) -> dict[str, Any]: 
    ...

@overload
def inspect(obj: Texture) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: UniformBatch) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: ComputePipeline) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: Program) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: VertexArray) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: Sampler) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: Query) -> dict[str, str | int]: 
    ...

@overload
def inspect(obj: Sync) -> dict[str, str]: 
    ...

def inspect(obj: object) -> dict[str, Any] | None: ...

# --- Classes ---

class Context:
    os_make_current_cb: Any
    os_release_cb: Any
    def __init__(self, loader: Any, os_make_current_cb: Any = None, os_release_cb: Any = None) -> None: ...
    def make_current(self) -> None: ...
    def __enter__(self) -> Context: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class Buffer:
    def __init__(
        self,
        size: int,
        data: _BufferProtocol | None = None,
        target: int = ...,
        usage: int = ...,
    ) -> None: ...
    def write(self, data: _BufferProtocol, offset: int = 0) -> None: ...
    def bind_base(self, index: int) -> None: ...
    def map(self) -> memoryview: ...

class Sampler:
    def __init__(
        self,
        min_filter: int = ...,
        mag_filter: int = ...,
        wrap_s: int = ...,
        wrap_t: int = ...,
    ) -> None: ...

class Texture:
    def __init__(self, target: int = ...) -> None: ...
    def upload(
        self,
        width: int,
        height: int,
        internal_format: int,
        format: int,
        type: int,
        data: _BufferProtocol | None = None,
        level: int = 0,
        depth: int = 0,
    ) -> None: ...
    def bind(self, unit: int, sampler: Sampler | None = None) -> None: ...
    def generate_mipmap(self) -> None: ...

class Program:
    def __init__(self, vertex_shader: str, fragment_shader: str) -> None: ...
    def get_uniform_location(self, name: str) -> int: ...

class VertexArray:
    def __init__(self) -> None: ...
    def bind_attribute(
        self,
        location: int,
        buffer: Buffer,
        size: int,
        type: int,
        normalized: int = 0,
        stride: int = 0,
        offset: int = 0,
        divisor: int = 0,
    ) -> None: ...
    def bind_index_buffer(self, buffer: Buffer) -> None: ...

class UniformBatch:
    def __init__(self, max_bindings: int, max_bytes: int) -> None: ...
    def add(self, func_id: int, location: int, count: int, size: int) -> int: ...
    @property
    def data(self) -> memoryview: ...

class Pipeline:
    def __init__(
        self,
        program: Program,
        vao: VertexArray,
        topology: int = ...,
        index_type: int = ...,
        depth_test: int = 0,
        depth_write: int = 1,
        depth_func: int = ...,
        cull: int = 0,
        cull_mode: int = ...,
        front_face: int = CCW,
        stencil_test: int = 0,
        stencil_func: int = ...,
        stencil_ref: int = 0,
        stencil_read_mask: int = 0xFFFFFFFF,
        stencil_write_mask: int = 0xFFFFFFFF,
        stencil_fail: int = ...,
        stencil_zfail: int = ...,
        stencil_zpass: int = ...,
        blend: int = 0,
        blend_src_rgb: int = ...,
        blend_dst_rgb: int = ...,
        blend_src_alpha: int = ...,
        blend_dst_alpha: int = ...,
        blend_eq_rgb: int = ...,
        blend_eq_alpha: int = ...,
    ) -> None: ...
    def upload_uniforms(self, batch: UniformBatch) -> None: ...
    def draw(self) -> None: ...
    @property
    def params(self) -> memoryview: ...

class ComputePipeline:
    def __init__(self, source: str) -> None: ...
    def dispatch(self, x: int, y: int, z: int) -> None: ...

class Framebuffer:
    def __init__(self) -> None: ...
    def attach_texture(
        self, attachment: int, texture: Texture, level: int = 0
    ) -> None: ...
    def check_status(self) -> bool: ...
    def bind(self) -> None: ...

class Sync:
    def __init__(self) -> None: ...
    def wait(self, timeout_sec: float | None = None) -> int: ...

class Query:
    def __init__(self, target: int = ...) -> None: ...
    def begin(self) -> None: ...
    def end(self) -> None: ...
    def record_timestamp(self) -> None: ...
    def is_ready(self) -> bool: ...
    def get_result(self) -> int: ...

# src/caravangl/__init__.pyi

__all__ = [
    "Context",
    "Buffer",
    "Sampler",
    "Texture",
    "Program",
    "VertexArray",
    "UniformBatch",
    "Pipeline",
    "Framebuffer",
    "Sync",
    "Query",
    "enable_debug",
    "context",
    "inspect",
    "clear",
    "clear_color",
    "viewport",
    "bind_default_framebuffer",
    "get_active_context",
    # @GENERATED_CONSTANTS_START@
    "FALSE",
    "TRUE",
    "INVALID_INDEX",
    "TIMEOUT_IGNORED",
    "INVALID_ENUM_VALUE",
    "PERSISTENT_WRITE_FLAGS",
    "SPEC_MIN_MAP_BUFFER_ALIGNMENT",
    "SPEC_MIN_TEXEL_OFFSET",
    "SPEC_MAX_TEXEL_OFFSET",
    "SPEC_MIN_UBO_BINDINGS",
    "SPEC_MIN_TEXTURE_UNITS",
    "SPEC_MIN_COMBINED_TEXTURE_UNITS",
    "SPEC_MIN_COLOR_ATTACHMENTS",
    "DONT_CARE",
    "BYTE",
    "UNSIGNED_BYTE",
    "SHORT",
    "UNSIGNED_SHORT",
    "INT",
    "UNSIGNED_INT",
    "FLOAT",
    "DOUBLE",
    "HALF_FLOAT",
    "FIXED",
    "INT_2_10_10_10_REV",
    "UNSIGNED_INT_2_10_10_10_REV",
    "UNSIGNED_INT_10F_11F_11F_REV",
    "UNSIGNED_BYTE_3_3_2",
    "UNSIGNED_SHORT_4_4_4_4",
    "UNSIGNED_SHORT_5_5_5_1",
    "UNSIGNED_INT_8_8_8_8",
    "UNSIGNED_INT_10_10_10_2",
    "UNSIGNED_BYTE_2_3_3_REV",
    "UNSIGNED_SHORT_5_6_5",
    "UNSIGNED_SHORT_5_6_5_REV",
    "UNSIGNED_SHORT_4_4_4_4_REV",
    "UNSIGNED_SHORT_1_5_5_5_REV",
    "UNSIGNED_INT_8_8_8_8_REV",
    "UNSIGNED_INT_24_8",
    "FLOAT_32_UNSIGNED_INT_24_8_REV",
    "POINTS",
    "LINES",
    "LINE_LOOP",
    "LINE_STRIP",
    "TRIANGLES",
    "TRIANGLE_STRIP",
    "TRIANGLE_FAN",
    "LINES_ADJACENCY",
    "LINE_STRIP_ADJACENCY",
    "TRIANGLES_ADJACENCY",
    "TRIANGLE_STRIP_ADJACENCY",
    "PATCHES",
    "ZERO",
    "ONE",
    "SRC_COLOR",
    "ONE_MINUS_SRC_COLOR",
    "SRC_ALPHA",
    "ONE_MINUS_SRC_ALPHA",
    "DST_ALPHA",
    "ONE_MINUS_DST_ALPHA",
    "DST_COLOR",
    "ONE_MINUS_DST_COLOR",
    "SRC_ALPHA_SATURATE",
    "CONSTANT_COLOR",
    "ONE_MINUS_CONSTANT_COLOR",
    "CONSTANT_ALPHA",
    "ONE_MINUS_CONSTANT_ALPHA",
    "SRC1_COLOR",
    "ONE_MINUS_SRC1_COLOR",
    "SRC1_ALPHA",
    "ONE_MINUS_SRC1_ALPHA",
    "FUNC_ADD",
    "FUNC_SUBTRACT",
    "FUNC_REVERSE_SUBTRACT",
    "MIN",
    "MAX",
    "DEPTH_BUFFER_BIT",
    "STENCIL_BUFFER_BIT",
    "COLOR_BUFFER_BIT",
    "COLOR",
    "DEPTH",
    "STENCIL",
    "NO_ERROR",
    "INVALID_ENUM",
    "INVALID_VALUE",
    "INVALID_OPERATION",
    "STACK_OVERFLOW",
    "STACK_UNDERFLOW",
    "OUT_OF_MEMORY",
    "INVALID_FRAMEBUFFER_OPERATION",
    "CONTEXT_LOST",
    "VENDOR",
    "RENDERER",
    "VERSION",
    "EXTENSIONS",
    "SHADING_LANGUAGE_VERSION",
    "CW",
    "CCW",
    "FRONT",
    "BACK",
    "FRONT_AND_BACK",
    "POINT",
    "LINE",
    "FILL",
    "NEVER",
    "LESS",
    "EQUAL",
    "LEQUAL",
    "GREATER",
    "NOTEQUAL",
    "GEQUAL",
    "ALWAYS",
    "KEEP",
    "REPLACE",
    "INCR",
    "DECR",
    "INVERT",
    "INCR_WRAP",
    "DECR_WRAP",
    "CULL_FACE",
    "DEPTH_TEST",
    "STENCIL_TEST",
    "BLEND",
    "SCISSOR_TEST",
    "COLOR_LOGIC_OP",
    "DITHER",
    "LINE_SMOOTH",
    "POLYGON_SMOOTH",
    "POLYGON_OFFSET_POINT",
    "POLYGON_OFFSET_LINE",
    "POLYGON_OFFSET_FILL",
    "MULTISAMPLE",
    "SAMPLE_ALPHA_TO_COVERAGE",
    "SAMPLE_ALPHA_TO_ONE",
    "SAMPLE_COVERAGE",
    "SAMPLE_SHADING",
    "SAMPLE_MASK",
    "PRIMITIVE_RESTART",
    "PRIMITIVE_RESTART_FIXED_INDEX",
    "RASTERIZER_DISCARD",
    "FRAMEBUFFER_SRGB",
    "DEPTH_CLAMP",
    "TEXTURE_CUBE_MAP_SEAMLESS",
    "PROGRAM_POINT_SIZE",
    "DEBUG_OUTPUT",
    "DEBUG_OUTPUT_SYNCHRONOUS",
    "VIEWPORT",
    "DEPTH_RANGE",
    "DEPTH_WRITEMASK",
    "DEPTH_CLEAR_VALUE",
    "DEPTH_FUNC",
    "STENCIL_CLEAR_VALUE",
    "STENCIL_FUNC",
    "STENCIL_VALUE_MASK",
    "STENCIL_FAIL",
    "STENCIL_PASS_DEPTH_FAIL",
    "STENCIL_PASS_DEPTH_PASS",
    "STENCIL_REF",
    "STENCIL_WRITEMASK",
    "SCISSOR_BOX",
    "COLOR_CLEAR_VALUE",
    "COLOR_WRITEMASK",
    "MAX_TEXTURE_SIZE",
    "MAX_VIEWPORT_DIMS",
    "SUBPIXEL_BITS",
    "MAX_ELEMENTS_VERTICES",
    "MAX_ELEMENTS_INDICES",
    "MAX_3D_TEXTURE_SIZE",
    "MAX_DRAW_BUFFERS",
    "MAX_VERTEX_ATTRIBS",
    "MAX_TEXTURE_IMAGE_UNITS",
    "MAX_FRAGMENT_UNIFORM_COMPONENTS",
    "MAX_VERTEX_UNIFORM_COMPONENTS",
    "MAX_VARYING_FLOATS",
    "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
    "MAX_COMBINED_TEXTURE_IMAGE_UNITS",
    "MAX_RENDERBUFFER_SIZE",
    "MAX_COLOR_ATTACHMENTS",
    "MAX_SAMPLES",
    "MAX_RECTANGLE_TEXTURE_SIZE",
    "MAX_TEXTURE_LOD_BIAS",
    "MAX_CUBE_MAP_TEXTURE_SIZE",
    "MAX_ARRAY_TEXTURE_LAYERS",
    "MAX_TEXTURE_BUFFER_SIZE",
    "MAX_UNIFORM_BUFFER_BINDINGS",
    "MAX_UNIFORM_BLOCK_SIZE",
    "MAX_COMBINED_UNIFORM_BLOCKS",
    "MAX_VERTEX_UNIFORM_BLOCKS",
    "MAX_GEOMETRY_UNIFORM_BLOCKS",
    "MAX_FRAGMENT_UNIFORM_BLOCKS",
    "MAX_SHADER_STORAGE_BUFFER_BINDINGS",
    "MAX_SHADER_STORAGE_BLOCK_SIZE",
    "MAX_COMPUTE_SHADER_STORAGE_BLOCKS",
    "MAX_COMPUTE_UNIFORM_BLOCKS",
    "MAX_COMPUTE_TEXTURE_IMAGE_UNITS",
    "MAX_COMPUTE_IMAGE_UNIFORMS",
    "MAX_COMPUTE_WORK_GROUP_SIZE",
    "MAX_COMPUTE_WORK_GROUP_INVOCATIONS",
    "MAX_IMAGE_UNITS",
    "MAX_VERTEX_IMAGE_UNIFORMS",
    "MAX_FRAGMENT_IMAGE_UNIFORMS",
    "MAX_COMBINED_IMAGE_UNIFORMS",
    "MAX_GEOMETRY_IMAGE_UNIFORMS",
    "MAX_TESS_CONTROL_IMAGE_UNIFORMS",
    "MAX_TESS_EVALUATION_IMAGE_UNIFORMS",
    "MAX_VERTEX_SHADER_STORAGE_BLOCKS",
    "MAX_FRAGMENT_SHADER_STORAGE_BLOCKS",
    "MAX_GEOMETRY_SHADER_STORAGE_BLOCKS",
    "MAX_VERTEX_ATOMIC_COUNTERS",
    "MAX_FRAGMENT_ATOMIC_COUNTERS",
    "MAX_COMBINED_ATOMIC_COUNTERS",
    "MAX_ATOMIC_COUNTER_BUFFER_SIZE",
    "MAX_VERTEX_ATTRIB_RELATIVE_OFFSET",
    "MAX_VERTEX_ATTRIB_BINDINGS",
    "MAX_VERTEX_ATTRIB_STRIDE",
    "MAX_DEBUG_MESSAGE_LENGTH",
    "MAX_DEBUG_LOGGED_MESSAGES",
    "MAX_DEBUG_GROUP_STACK_DEPTH",
    "MAX_LABEL_LENGTH",
    "NUM_EXTENSIONS",
    "MAJOR_VERSION",
    "MINOR_VERSION",
    "CONTEXT_FLAGS",
    "CONTEXT_PROFILE_MASK",
    "CURRENT_PROGRAM",
    "DRAW_INDIRECT_BUFFER_BINDING",
    "ACTIVE_ATOMIC_COUNTER_BUFFERS",
    "CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT",
    "CONTEXT_FLAG_DEBUG_BIT",
    "CONTEXT_FLAG_ROBUST_ACCESS_BIT",
    "CONTEXT_CORE_PROFILE_BIT",
    "CONTEXT_COMPATIBILITY_PROFILE_BIT",
    "TEXTURE_1D",
    "TEXTURE_2D",
    "TEXTURE_3D",
    "TEXTURE_1D_ARRAY",
    "TEXTURE_2D_ARRAY",
    "TEXTURE_RECTANGLE",
    "TEXTURE_CUBE_MAP",
    "TEXTURE_CUBE_MAP_ARRAY",
    "TEXTURE_2D_MULTISAMPLE",
    "TEXTURE_2D_MULTISAMPLE_ARRAY",
    "TEXTURE_BUFFER",
    "PROXY_TEXTURE_1D",
    "PROXY_TEXTURE_2D",
    "PROXY_TEXTURE_3D",
    "PROXY_TEXTURE_CUBE_MAP",
    "TEXTURE_CUBE_MAP_POSITIVE_X",
    "TEXTURE_CUBE_MAP_NEGATIVE_X",
    "TEXTURE_CUBE_MAP_POSITIVE_Y",
    "TEXTURE_CUBE_MAP_NEGATIVE_Y",
    "TEXTURE_CUBE_MAP_POSITIVE_Z",
    "TEXTURE_CUBE_MAP_NEGATIVE_Z",
    "TEXTURE_MIN_FILTER",
    "TEXTURE_MAG_FILTER",
    "TEXTURE_WRAP_S",
    "TEXTURE_WRAP_T",
    "TEXTURE_WRAP_R",
    "TEXTURE_BASE_LEVEL",
    "TEXTURE_MAX_LEVEL",
    "TEXTURE_MIN_LOD",
    "TEXTURE_MAX_LOD",
    "TEXTURE_LOD_BIAS",
    "TEXTURE_COMPARE_MODE",
    "TEXTURE_COMPARE_FUNC",
    "TEXTURE_SWIZZLE_R",
    "TEXTURE_SWIZZLE_G",
    "TEXTURE_SWIZZLE_B",
    "TEXTURE_SWIZZLE_A",
    "TEXTURE_SWIZZLE_RGBA",
    "TEXTURE_BORDER_COLOR",
    "TEXTURE_MAX_ANISOTROPY",
    "DEPTH_STENCIL_TEXTURE_MODE",
    "NEAREST",
    "LINEAR",
    "NEAREST_MIPMAP_NEAREST",
    "LINEAR_MIPMAP_NEAREST",
    "NEAREST_MIPMAP_LINEAR",
    "LINEAR_MIPMAP_LINEAR",
    "REPEAT",
    "CLAMP_TO_EDGE",
    "CLAMP_TO_BORDER",
    "MIRRORED_REPEAT",
    "MIRROR_CLAMP_TO_EDGE",
    "COMPARE_REF_TO_TEXTURE",
    "TEXTURE_COMPARE_MODE_NONE",
    "RED_COMPONENT",
    "GREEN",
    "BLUE",
    "ALPHA",
    "TEXTURE0",
    "TEXTURE1",
    "TEXTURE2",
    "TEXTURE3",
    "TEXTURE4",
    "TEXTURE5",
    "TEXTURE6",
    "TEXTURE7",
    "TEXTURE8",
    "TEXTURE9",
    "TEXTURE10",
    "TEXTURE11",
    "TEXTURE12",
    "TEXTURE13",
    "TEXTURE14",
    "TEXTURE15",
    "TEXTURE16",
    "TEXTURE17",
    "TEXTURE18",
    "TEXTURE19",
    "TEXTURE20",
    "TEXTURE21",
    "TEXTURE22",
    "TEXTURE23",
    "TEXTURE24",
    "TEXTURE25",
    "TEXTURE26",
    "TEXTURE27",
    "TEXTURE28",
    "TEXTURE29",
    "TEXTURE30",
    "TEXTURE31",
    "R8",
    "R8_SNORM",
    "R16",
    "R16_SNORM",
    "RG8",
    "RG8_SNORM",
    "RG16",
    "RG16_SNORM",
    "R3_G3_B2",
    "RGB4",
    "RGB5",
    "RGB8",
    "RGB8_SNORM",
    "RGB10",
    "RGB12",
    "RGB16",
    "RGB16_SNORM",
    "RGBA2",
    "RGBA4",
    "RGB5_A1",
    "RGBA8",
    "RGBA8_SNORM",
    "RGB10_A2",
    "RGB10_A2UI",
    "RGBA12",
    "RGBA16",
    "RGBA16_SNORM",
    "SRGB8",
    "SRGB8_ALPHA8",
    "R16F",
    "RG16F",
    "RGB16F",
    "RGBA16F",
    "R32F",
    "RG32F",
    "RGB32F",
    "RGBA32F",
    "R11F_G11F_B10F",
    "RGB9_E5",
    "R8I",
    "R8UI",
    "R16I",
    "R16UI",
    "R32I",
    "R32UI",
    "RG8I",
    "RG8UI",
    "RG16I",
    "RG16UI",
    "RG32I",
    "RG32UI",
    "RGB8I",
    "RGB8UI",
    "RGB16I",
    "RGB16UI",
    "RGB32I",
    "RGB32UI",
    "RGBA8I",
    "RGBA8UI",
    "RGBA16I",
    "RGBA16UI",
    "RGBA32I",
    "RGBA32UI",
    "DEPTH_COMPONENT16",
    "DEPTH_COMPONENT24",
    "DEPTH_COMPONENT32",
    "DEPTH_COMPONENT32F",
    "DEPTH24_STENCIL8",
    "DEPTH32F_STENCIL8",
    "STENCIL_INDEX1",
    "STENCIL_INDEX4",
    "STENCIL_INDEX8",
    "STENCIL_INDEX16",
    "COMPRESSED_RED",
    "COMPRESSED_RG",
    "COMPRESSED_RGB",
    "COMPRESSED_RGBA",
    "COMPRESSED_SRGB",
    "COMPRESSED_SRGB_ALPHA",
    "COMPRESSED_RED_RGTC1",
    "COMPRESSED_SIGNED_RED_RGTC1",
    "COMPRESSED_RG_RGTC2",
    "COMPRESSED_SIGNED_RG_RGTC2",
    "COMPRESSED_RGBA_BPTC_UNORM",
    "COMPRESSED_SRGB_ALPHA_BPTC_UNORM",
    "COMPRESSED_RGB_BPTC_SIGNED_FLOAT",
    "COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT",
    "RED",
    "RG",
    "RGB",
    "RGBA",
    "BGR",
    "BGRA",
    "RED_INTEGER",
    "RG_INTEGER",
    "RGB_INTEGER",
    "RGBA_INTEGER",
    "BGR_INTEGER",
    "BGRA_INTEGER",
    "STENCIL_INDEX",
    "DEPTH_COMPONENT",
    "DEPTH_STENCIL",
    "UNPACK_SWAP_BYTES",
    "UNPACK_LSB_FIRST",
    "UNPACK_ROW_LENGTH",
    "UNPACK_SKIP_ROWS",
    "UNPACK_SKIP_PIXELS",
    "UNPACK_ALIGNMENT",
    "UNPACK_IMAGE_HEIGHT",
    "UNPACK_SKIP_IMAGES",
    "PACK_SWAP_BYTES",
    "PACK_LSB_FIRST",
    "PACK_ROW_LENGTH",
    "PACK_SKIP_ROWS",
    "PACK_SKIP_PIXELS",
    "PACK_ALIGNMENT",
    "PACK_IMAGE_HEIGHT",
    "PACK_SKIP_IMAGES",
    "ARRAY_BUFFER",
    "ELEMENT_ARRAY_BUFFER",
    "PIXEL_PACK_BUFFER",
    "PIXEL_UNPACK_BUFFER",
    "UNIFORM_BUFFER",
    "TRANSFORM_FEEDBACK_BUFFER",
    "COPY_READ_BUFFER",
    "COPY_WRITE_BUFFER",
    "DRAW_INDIRECT_BUFFER",
    "SHADER_STORAGE_BUFFER",
    "DISPATCH_INDIRECT_BUFFER",
    "QUERY_BUFFER",
    "ATOMIC_COUNTER_BUFFER",
    "STREAM_DRAW",
    "STREAM_READ",
    "STREAM_COPY",
    "STATIC_DRAW",
    "STATIC_READ",
    "STATIC_COPY",
    "DYNAMIC_DRAW",
    "DYNAMIC_READ",
    "DYNAMIC_COPY",
    "MAP_READ_BIT",
    "MAP_WRITE_BIT",
    "MAP_INVALIDATE_RANGE_BIT",
    "MAP_INVALIDATE_BUFFER_BIT",
    "MAP_FLUSH_EXPLICIT_BIT",
    "MAP_UNSYNCHRONIZED_BIT",
    "MAP_PERSISTENT_BIT",
    "MAP_COHERENT_BIT",
    "DYNAMIC_STORAGE_BIT",
    "CLIENT_STORAGE_BIT",
    "BUFFER_SIZE",
    "BUFFER_USAGE",
    "BUFFER_ACCESS",
    "BUFFER_MAPPED",
    "BUFFER_MAP_POINTER",
    "BUFFER_ACCESS_FLAGS",
    "BUFFER_MAP_LENGTH",
    "BUFFER_MAP_OFFSET",
    "BUFFER_IMMUTABLE_STORAGE",
    "BUFFER_STORAGE_FLAGS",
    "FRAMEBUFFER",
    "READ_FRAMEBUFFER",
    "DRAW_FRAMEBUFFER",
    "RENDERBUFFER",
    "COLOR_ATTACHMENT0",
    "COLOR_ATTACHMENT1",
    "COLOR_ATTACHMENT2",
    "COLOR_ATTACHMENT3",
    "COLOR_ATTACHMENT4",
    "COLOR_ATTACHMENT5",
    "COLOR_ATTACHMENT6",
    "COLOR_ATTACHMENT7",
    "COLOR_ATTACHMENT8",
    "COLOR_ATTACHMENT9",
    "COLOR_ATTACHMENT10",
    "COLOR_ATTACHMENT11",
    "COLOR_ATTACHMENT12",
    "COLOR_ATTACHMENT13",
    "COLOR_ATTACHMENT14",
    "COLOR_ATTACHMENT15",
    "DEPTH_ATTACHMENT",
    "STENCIL_ATTACHMENT",
    "DEPTH_STENCIL_ATTACHMENT",
    "FRAMEBUFFER_COMPLETE",
    "FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
    "FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
    "FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",
    "FRAMEBUFFER_INCOMPLETE_READ_BUFFER",
    "FRAMEBUFFER_UNSUPPORTED",
    "FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
    "FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS",
    "FRAMEBUFFER_DEFAULT",
    "FRAMEBUFFER_UNDEFINED",
    "FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE",
    "FRAMEBUFFER_ATTACHMENT_OBJECT_NAME",
    "FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL",
    "FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE",
    "FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER",
    "FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING",
    "FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE",
    "FRAMEBUFFER_ATTACHMENT_RED_SIZE",
    "FRAMEBUFFER_ATTACHMENT_GREEN_SIZE",
    "FRAMEBUFFER_ATTACHMENT_BLUE_SIZE",
    "FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE",
    "FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE",
    "FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE",
    "RENDERBUFFER_WIDTH",
    "RENDERBUFFER_HEIGHT",
    "RENDERBUFFER_INTERNAL_FORMAT",
    "RENDERBUFFER_RED_SIZE",
    "RENDERBUFFER_GREEN_SIZE",
    "RENDERBUFFER_BLUE_SIZE",
    "RENDERBUFFER_ALPHA_SIZE",
    "RENDERBUFFER_DEPTH_SIZE",
    "RENDERBUFFER_STENCIL_SIZE",
    "RENDERBUFFER_SAMPLES",
    "FRAGMENT_SHADER",
    "VERTEX_SHADER",
    "GEOMETRY_SHADER",
    "TESS_EVALUATION_SHADER",
    "TESS_CONTROL_SHADER",
    "COMPUTE_SHADER",
    "SHADER_TYPE",
    "DELETE_STATUS",
    "COMPILE_STATUS",
    "INFO_LOG_LENGTH",
    "SHADER_SOURCE_LENGTH",
    "LINK_STATUS",
    "VALIDATE_STATUS",
    "ATTACHED_SHADERS",
    "ACTIVE_UNIFORMS",
    "ACTIVE_UNIFORM_MAX_LENGTH",
    "ACTIVE_ATTRIBUTES",
    "ACTIVE_ATTRIBUTE_MAX_LENGTH",
    "FLOAT_VEC2",
    "FLOAT_VEC3",
    "FLOAT_VEC4",
    "DOUBLE_VEC2",
    "DOUBLE_VEC3",
    "DOUBLE_VEC4",
    "INT_VEC2",
    "INT_VEC3",
    "INT_VEC4",
    "UNSIGNED_INT_VEC2",
    "UNSIGNED_INT_VEC3",
    "UNSIGNED_INT_VEC4",
    "BOOL",
    "BOOL_VEC2",
    "BOOL_VEC3",
    "BOOL_VEC4",
    "FLOAT_MAT2",
    "FLOAT_MAT3",
    "FLOAT_MAT4",
    "FLOAT_MAT2x3",
    "FLOAT_MAT2x4",
    "FLOAT_MAT3x2",
    "FLOAT_MAT3x4",
    "FLOAT_MAT4x2",
    "FLOAT_MAT4x3",
    "DOUBLE_MAT2",
    "DOUBLE_MAT3",
    "DOUBLE_MAT4",
    "SAMPLER_1D",
    "SAMPLER_2D",
    "SAMPLER_3D",
    "SAMPLER_CUBE",
    "SAMPLER_1D_SHADOW",
    "SAMPLER_2D_SHADOW",
    "UNIFORM",
    "UNIFORM_BLOCK",
    "PROGRAM_INPUT",
    "PROGRAM_OUTPUT",
    "BUFFER_VARIABLE",
    "SHADER_STORAGE_BLOCK",
    "VERTEX_SUBROUTINE",
    "TESS_CONTROL_SUBROUTINE",
    "TESS_EVALUATION_SUBROUTINE",
    "GEOMETRY_SUBROUTINE",
    "FRAGMENT_SUBROUTINE",
    "COMPUTE_SUBROUTINE",
    "VERTEX_SUBROUTINE_UNIFORM",
    "TESS_CONTROL_SUBROUTINE_UNIFORM",
    "TESS_EVALUATION_SUBROUTINE_UNIFORM",
    "GEOMETRY_SUBROUTINE_UNIFORM",
    "FRAGMENT_SUBROUTINE_UNIFORM",
    "COMPUTE_SUBROUTINE_UNIFORM",
    "TRANSFORM_FEEDBACK_VARYING",
    "ACTIVE_RESOURCES",
    "MAX_NAME_LENGTH",
    "MAX_NUM_ACTIVE_VARIABLES",
    "NAME_LENGTH",
    "TYPE",
    "ARRAY_SIZE",
    "OFFSET",
    "BLOCK_INDEX",
    "ARRAY_STRIDE",
    "MATRIX_STRIDE",
    "IS_ROW_MAJOR",
    "ATOMIC_COUNTER_BUFFER_INDEX",
    "BUFFER_BINDING",
    "BUFFER_DATA_SIZE",
    "NUM_ACTIVE_VARIABLES",
    "ACTIVE_VARIABLES",
    "REFERENCED_BY_VERTEX_SHADER",
    "REFERENCED_BY_TESS_CONTROL_SHADER",
    "REFERENCED_BY_TESS_EVALUATION_SHADER",
    "REFERENCED_BY_GEOMETRY_SHADER",
    "REFERENCED_BY_FRAGMENT_SHADER",
    "REFERENCED_BY_COMPUTE_SHADER",
    "TOP_LEVEL_ARRAY_SIZE",
    "TOP_LEVEL_ARRAY_STRIDE",
    "LOCATION",
    "LOCATION_INDEX",
    "IS_PER_PATCH",
    "VERTEX_ATTRIB_ARRAY_ENABLED",
    "VERTEX_ATTRIB_ARRAY_SIZE",
    "VERTEX_ATTRIB_ARRAY_STRIDE",
    "VERTEX_ATTRIB_ARRAY_TYPE",
    "VERTEX_ATTRIB_ARRAY_NORMALIZED",
    "VERTEX_ATTRIB_ARRAY_POINTER",
    "VERTEX_ATTRIB_ARRAY_BUFFER_BINDING",
    "VERTEX_ATTRIB_ARRAY_INTEGER",
    "VERTEX_ATTRIB_ARRAY_DIVISOR",
    "VERTEX_ATTRIB_ARRAY_LONG",
    "VERTEX_ATTRIB_BINDING",
    "VERTEX_ATTRIB_RELATIVE_OFFSET",
    "VERTEX_BINDING_DIVISOR",
    "VERTEX_BINDING_OFFSET",
    "VERTEX_BINDING_STRIDE",
    "VERTEX_BINDING_BUFFER",
    "READ_ONLY",
    "WRITE_ONLY",
    "READ_WRITE",
    "VERTEX_ATTRIB_ARRAY_BARRIER_BIT",
    "ELEMENT_ARRAY_BARRIER_BIT",
    "UNIFORM_BARRIER_BIT",
    "TEXTURE_FETCH_BARRIER_BIT",
    "SHADER_IMAGE_ACCESS_BARRIER_BIT",
    "COMMAND_BARRIER_BIT",
    "PIXEL_BUFFER_BARRIER_BIT",
    "TEXTURE_UPDATE_BARRIER_BIT",
    "BUFFER_UPDATE_BARRIER_BIT",
    "FRAMEBUFFER_BARRIER_BIT",
    "TRANSFORM_FEEDBACK_BARRIER_BIT",
    "ATOMIC_COUNTER_BARRIER_BIT",
    "SHADER_STORAGE_BARRIER_BIT",
    "CLIENT_MAPPED_BUFFER_BARRIER_BIT",
    "QUERY_BUFFER_BARRIER_BIT",
    "ALL_BARRIER_BITS",
    "ALREADY_SIGNALED",
    "TIMEOUT_EXPIRED",
    "CONDITION_SATISFIED",
    "WAIT_FAILED",
    "SYNC_FLUSH_COMMANDS_BIT",
    "SYNC_GPU_COMMANDS_COMPLETE",
    "SYNC_STATUS",
    "SYNC_CONDITION",
    "SYNC_FLAGS",
    "SYNC_FENCE",
    "OBJECT_TYPE",
    "SAMPLES_PASSED",
    "ANY_SAMPLES_PASSED",
    "ANY_SAMPLES_PASSED_CONSERVATIVE",
    "PRIMITIVES_GENERATED",
    "TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN",
    "TIME_ELAPSED",
    "TIMESTAMP",
    "QUERY_RESULT",
    "QUERY_RESULT_AVAILABLE",
    "QUERY_RESULT_NO_WAIT",
    "INTERLEAVED_ATTRIBS",
    "SEPARATE_ATTRIBS",
    "TRANSFORM_FEEDBACK",
    "PATCH_VERTICES",
    "PATCH_DEFAULT_INNER_LEVEL",
    "PATCH_DEFAULT_OUTER_LEVEL",
    "TESS_GEN_MODE",
    "TESS_GEN_SPACING",
    "TESS_GEN_VERTEX_ORDER",
    "TESS_GEN_POINT_MODE",
    "FIRST_VERTEX_CONVENTION",
    "LAST_VERTEX_CONVENTION",
    "PROVOKING_VERTEX",
    "CLEAR",
    "AND",
    "AND_REVERSE",
    "COPY",
    "AND_INVERTED",
    "NOOP",
    "XOR",
    "OR",
    "NOR",
    "EQUIV",
    "LOGIC_INVERT",
    "OR_REVERSE",
    "COPY_INVERTED",
    "OR_INVERTED",
    "NAND",
    "SET",
    "ATOMIC_COUNTER_BUFFER_BINDING",
    "ATOMIC_COUNTER_BUFFER_DATA_SIZE",
    "ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS",
    "UNSIGNED_INT_ATOMIC_COUNTER",
    "DEBUG_SOURCE_API",
    "DEBUG_SOURCE_WINDOW_SYSTEM",
    "DEBUG_SOURCE_SHADER_COMPILER",
    "DEBUG_SOURCE_THIRD_PARTY",
    "DEBUG_SOURCE_APPLICATION",
    "DEBUG_SOURCE_OTHER",
    "DEBUG_TYPE_ERROR",
    "DEBUG_TYPE_DEPRECATED_BEHAVIOR",
    "DEBUG_TYPE_UNDEFINED_BEHAVIOR",
    "DEBUG_TYPE_PORTABILITY",
    "DEBUG_TYPE_PERFORMANCE",
    "DEBUG_TYPE_OTHER",
    "DEBUG_TYPE_MARKER",
    "DEBUG_TYPE_PUSH_GROUP",
    "DEBUG_TYPE_POP_GROUP",
    "DEBUG_SEVERITY_HIGH",
    "DEBUG_SEVERITY_MEDIUM",
    "DEBUG_SEVERITY_LOW",
    "DEBUG_SEVERITY_NOTIFICATION",
    "DEBUG_LOGGED_MESSAGES",
    "DEBUG_NEXT_LOGGED_MESSAGE_LENGTH",
    "DEBUG_GROUP_STACK_DEPTH",
    "BUFFER_OBJECT",
    "SHADER_OBJECT",
    "PROGRAM_OBJECT",
    "VERTEX_ARRAY_OBJECT",
    "QUERY_OBJECT",
    "PROGRAM_PIPELINE_OBJECT",
    "SAMPLER_OBJECT",
    "DRAW_BUFFER0",
    "DRAW_BUFFER1",
    "DRAW_BUFFER2",
    "DRAW_BUFFER3",
    "DRAW_BUFFER4",
    "DRAW_BUFFER5",
    "DRAW_BUFFER6",
    "DRAW_BUFFER7",
    "DRAW_BUFFER8",
    "DRAW_BUFFER9",
    "DRAW_BUFFER10",
    "DRAW_BUFFER11",
    "DRAW_BUFFER12",
    "DRAW_BUFFER13",
    "DRAW_BUFFER14",
    "DRAW_BUFFER15",
    "BACK_LEFT",
    "BACK_RIGHT",
    "FRONT_LEFT",
    "FRONT_RIGHT",
    "LEFT",
    "RIGHT",
    "NONE",
    "UF_1I",
    "UF_2I",
    "UF_3I",
    "UF_4I",
    "UF_1B",
    "UF_2B",
    "UF_3B",
    "UF_4B",
    "UF_1U",
    "UF_2U",
    "UF_3U",
    "UF_4U",
    "UF_1F",
    "UF_2F",
    "UF_3F",
    "UF_4F",
    "UF_MAT2",
    "UF_MAT2x3",
    "UF_MAT2x4",
    "UF_MAT3x2",
    "UF_MAT3",
    "UF_MAT3x4",
    "UF_MAT4x2",
    "UF_MAT4x3",
    "UF_MAT4",
    "UF_MAT2_RM",
    "UF_MAT3_RM",
    "UF_MAT4_RM",
    "IF_INTERNAL_FORMAT",
    "IF_FORMAT",
    "IF_TYPE",
    "IF_BUFFER",
    "IF_COMPONENTS",
    "IF_PIXEL_SIZE",
    "IF_COLOR",
    "IF_FLAGS",
    "IF_CLEAR_TYPE",
    # @GENERATED_CONSTANTS_END@
]