# Automatically generated. DO NOT EDIT.
from typing import Final

# --- Core Constants ---
FALSE: Final[int]
TRUE: Final[int]
INVALID_INDEX: Final[int]
TIMEOUT_IGNORED: Final[int]
INVALID_ENUM_VALUE: Final[int]
PERSISTENT_WRITE_FLAGS: Final[int]
SPEC_MIN_MAP_BUFFER_ALIGNMENT: Final[int]
SPEC_MIN_TEXEL_OFFSET: Final[int]
SPEC_MAX_TEXEL_OFFSET: Final[int]
SPEC_MIN_UBO_BINDINGS: Final[int]
SPEC_MIN_TEXTURE_UNITS: Final[int]
SPEC_MIN_COMBINED_TEXTURE_UNITS: Final[int]
SPEC_MIN_COLOR_ATTACHMENTS: Final[int]

# --- GLHint ---
DONT_CARE: Final[int]

# --- GLDataType ---
BYTE: Final[int]
UNSIGNED_BYTE: Final[int]
SHORT: Final[int]
UNSIGNED_SHORT: Final[int]
INT: Final[int]
UNSIGNED_INT: Final[int]
FLOAT: Final[int]
DOUBLE: Final[int]
HALF_FLOAT: Final[int]
FIXED: Final[int]
INT_2_10_10_10_REV: Final[int]
UNSIGNED_INT_2_10_10_10_REV: Final[int]
UNSIGNED_INT_10F_11F_11F_REV: Final[int]
UNSIGNED_BYTE_3_3_2: Final[int]
UNSIGNED_SHORT_4_4_4_4: Final[int]
UNSIGNED_SHORT_5_5_5_1: Final[int]
UNSIGNED_INT_8_8_8_8: Final[int]
UNSIGNED_INT_10_10_10_2: Final[int]
UNSIGNED_BYTE_2_3_3_REV: Final[int]
UNSIGNED_SHORT_5_6_5: Final[int]
UNSIGNED_SHORT_5_6_5_REV: Final[int]
UNSIGNED_SHORT_4_4_4_4_REV: Final[int]
UNSIGNED_SHORT_1_5_5_5_REV: Final[int]
UNSIGNED_INT_8_8_8_8_REV: Final[int]
UNSIGNED_INT_24_8: Final[int]
FLOAT_32_UNSIGNED_INT_24_8_REV: Final[int]

# --- GLPrimitive ---
POINTS: Final[int]
LINES: Final[int]
LINE_LOOP: Final[int]
LINE_STRIP: Final[int]
TRIANGLES: Final[int]
TRIANGLE_STRIP: Final[int]
TRIANGLE_FAN: Final[int]
LINES_ADJACENCY: Final[int]
LINE_STRIP_ADJACENCY: Final[int]
TRIANGLES_ADJACENCY: Final[int]
TRIANGLE_STRIP_ADJACENCY: Final[int]
PATCHES: Final[int]

# --- GLBlendFactor ---
ZERO: Final[int]
ONE: Final[int]
SRC_COLOR: Final[int]
ONE_MINUS_SRC_COLOR: Final[int]
SRC_ALPHA: Final[int]
ONE_MINUS_SRC_ALPHA: Final[int]
DST_ALPHA: Final[int]
ONE_MINUS_DST_ALPHA: Final[int]
DST_COLOR: Final[int]
ONE_MINUS_DST_COLOR: Final[int]
SRC_ALPHA_SATURATE: Final[int]
CONSTANT_COLOR: Final[int]
ONE_MINUS_CONSTANT_COLOR: Final[int]
CONSTANT_ALPHA: Final[int]
ONE_MINUS_CONSTANT_ALPHA: Final[int]
SRC1_COLOR: Final[int]
ONE_MINUS_SRC1_COLOR: Final[int]
SRC1_ALPHA: Final[int]
ONE_MINUS_SRC1_ALPHA: Final[int]

# --- GLBlendEquation ---
FUNC_ADD: Final[int]
FUNC_SUBTRACT: Final[int]
FUNC_REVERSE_SUBTRACT: Final[int]
MIN: Final[int]
MAX: Final[int]

# --- GLClearMask ---
DEPTH_BUFFER_BIT: Final[int]
STENCIL_BUFFER_BIT: Final[int]
COLOR_BUFFER_BIT: Final[int]

# --- GLClearBufferTarget ---
COLOR: Final[int]
DEPTH: Final[int]
STENCIL: Final[int]

# --- GLError ---
NO_ERROR: Final[int]
INVALID_ENUM: Final[int]
INVALID_VALUE: Final[int]
INVALID_OPERATION: Final[int]
STACK_OVERFLOW: Final[int]
STACK_UNDERFLOW: Final[int]
OUT_OF_MEMORY: Final[int]
INVALID_FRAMEBUFFER_OPERATION: Final[int]
CONTEXT_LOST: Final[int]

# --- GLStringName ---
VENDOR: Final[int]
RENDERER: Final[int]
VERSION: Final[int]
EXTENSIONS: Final[int]
SHADING_LANGUAGE_VERSION: Final[int]

# --- GLFrontFaceDirection ---
CW: Final[int]
CCW: Final[int]

# --- GLFace ---
FRONT: Final[int]
BACK: Final[int]
FRONT_AND_BACK: Final[int]

# --- GLPolygonMode ---
POINT: Final[int]
LINE: Final[int]
FILL: Final[int]

# --- GLCompareFunction ---
NEVER: Final[int]
LESS: Final[int]
EQUAL: Final[int]
LEQUAL: Final[int]
GREATER: Final[int]
NOTEQUAL: Final[int]
GEQUAL: Final[int]
ALWAYS: Final[int]

# --- GLStencilOp ---
KEEP: Final[int]
REPLACE: Final[int]
INCR: Final[int]
DECR: Final[int]
INVERT: Final[int]
INCR_WRAP: Final[int]
DECR_WRAP: Final[int]

# --- GLCapability ---
CULL_FACE: Final[int]
DEPTH_TEST: Final[int]
STENCIL_TEST: Final[int]
BLEND: Final[int]
SCISSOR_TEST: Final[int]
COLOR_LOGIC_OP: Final[int]
DITHER: Final[int]
LINE_SMOOTH: Final[int]
POLYGON_SMOOTH: Final[int]
POLYGON_OFFSET_POINT: Final[int]
POLYGON_OFFSET_LINE: Final[int]
POLYGON_OFFSET_FILL: Final[int]
MULTISAMPLE: Final[int]
SAMPLE_ALPHA_TO_COVERAGE: Final[int]
SAMPLE_ALPHA_TO_ONE: Final[int]
SAMPLE_COVERAGE: Final[int]
SAMPLE_SHADING: Final[int]
SAMPLE_MASK: Final[int]
PRIMITIVE_RESTART: Final[int]
PRIMITIVE_RESTART_FIXED_INDEX: Final[int]
RASTERIZER_DISCARD: Final[int]
FRAMEBUFFER_SRGB: Final[int]
DEPTH_CLAMP: Final[int]
TEXTURE_CUBE_MAP_SEAMLESS: Final[int]
PROGRAM_POINT_SIZE: Final[int]
DEBUG_OUTPUT: Final[int]
DEBUG_OUTPUT_SYNCHRONOUS: Final[int]

# --- GLGetParameter ---
VIEWPORT: Final[int]
DEPTH_RANGE: Final[int]
DEPTH_WRITEMASK: Final[int]
DEPTH_CLEAR_VALUE: Final[int]
DEPTH_FUNC: Final[int]
STENCIL_CLEAR_VALUE: Final[int]
STENCIL_FUNC: Final[int]
STENCIL_VALUE_MASK: Final[int]
STENCIL_FAIL: Final[int]
STENCIL_PASS_DEPTH_FAIL: Final[int]
STENCIL_PASS_DEPTH_PASS: Final[int]
STENCIL_REF: Final[int]
STENCIL_WRITEMASK: Final[int]
SCISSOR_BOX: Final[int]
COLOR_CLEAR_VALUE: Final[int]
COLOR_WRITEMASK: Final[int]
MAX_TEXTURE_SIZE: Final[int]
MAX_VIEWPORT_DIMS: Final[int]
SUBPIXEL_BITS: Final[int]
MAX_ELEMENTS_VERTICES: Final[int]
MAX_ELEMENTS_INDICES: Final[int]
MAX_3D_TEXTURE_SIZE: Final[int]
MAX_DRAW_BUFFERS: Final[int]
MAX_VERTEX_ATTRIBS: Final[int]
MAX_TEXTURE_IMAGE_UNITS: Final[int]
MAX_FRAGMENT_UNIFORM_COMPONENTS: Final[int]
MAX_VERTEX_UNIFORM_COMPONENTS: Final[int]
MAX_VARYING_FLOATS: Final[int]
MAX_VERTEX_TEXTURE_IMAGE_UNITS: Final[int]
MAX_COMBINED_TEXTURE_IMAGE_UNITS: Final[int]
MAX_RENDERBUFFER_SIZE: Final[int]
MAX_COLOR_ATTACHMENTS: Final[int]
MAX_SAMPLES: Final[int]
MAX_RECTANGLE_TEXTURE_SIZE: Final[int]
MAX_TEXTURE_LOD_BIAS: Final[int]
MAX_CUBE_MAP_TEXTURE_SIZE: Final[int]
MAX_ARRAY_TEXTURE_LAYERS: Final[int]
MAX_TEXTURE_BUFFER_SIZE: Final[int]
MAX_UNIFORM_BUFFER_BINDINGS: Final[int]
MAX_UNIFORM_BLOCK_SIZE: Final[int]
MAX_COMBINED_UNIFORM_BLOCKS: Final[int]
MAX_VERTEX_UNIFORM_BLOCKS: Final[int]
MAX_GEOMETRY_UNIFORM_BLOCKS: Final[int]
MAX_FRAGMENT_UNIFORM_BLOCKS: Final[int]
MAX_SHADER_STORAGE_BUFFER_BINDINGS: Final[int]
MAX_SHADER_STORAGE_BLOCK_SIZE: Final[int]
MAX_COMPUTE_SHADER_STORAGE_BLOCKS: Final[int]
MAX_COMPUTE_UNIFORM_BLOCKS: Final[int]
MAX_COMPUTE_TEXTURE_IMAGE_UNITS: Final[int]
MAX_COMPUTE_IMAGE_UNIFORMS: Final[int]
MAX_COMPUTE_WORK_GROUP_SIZE: Final[int]
MAX_COMPUTE_WORK_GROUP_INVOCATIONS: Final[int]
MAX_IMAGE_UNITS: Final[int]
MAX_VERTEX_IMAGE_UNIFORMS: Final[int]
MAX_FRAGMENT_IMAGE_UNIFORMS: Final[int]
MAX_COMBINED_IMAGE_UNIFORMS: Final[int]
MAX_GEOMETRY_IMAGE_UNIFORMS: Final[int]
MAX_TESS_CONTROL_IMAGE_UNIFORMS: Final[int]
MAX_TESS_EVALUATION_IMAGE_UNIFORMS: Final[int]
MAX_VERTEX_SHADER_STORAGE_BLOCKS: Final[int]
MAX_FRAGMENT_SHADER_STORAGE_BLOCKS: Final[int]
MAX_GEOMETRY_SHADER_STORAGE_BLOCKS: Final[int]
MAX_VERTEX_ATOMIC_COUNTERS: Final[int]
MAX_FRAGMENT_ATOMIC_COUNTERS: Final[int]
MAX_COMBINED_ATOMIC_COUNTERS: Final[int]
MAX_ATOMIC_COUNTER_BUFFER_SIZE: Final[int]
MAX_VERTEX_ATTRIB_RELATIVE_OFFSET: Final[int]
MAX_VERTEX_ATTRIB_BINDINGS: Final[int]
MAX_VERTEX_ATTRIB_STRIDE: Final[int]
MAX_DEBUG_MESSAGE_LENGTH: Final[int]
MAX_DEBUG_LOGGED_MESSAGES: Final[int]
MAX_DEBUG_GROUP_STACK_DEPTH: Final[int]
MAX_LABEL_LENGTH: Final[int]
NUM_EXTENSIONS: Final[int]
MAJOR_VERSION: Final[int]
MINOR_VERSION: Final[int]
CONTEXT_FLAGS: Final[int]
CONTEXT_PROFILE_MASK: Final[int]
CURRENT_PROGRAM: Final[int]
DRAW_INDIRECT_BUFFER_BINDING: Final[int]
ACTIVE_ATOMIC_COUNTER_BUFFERS: Final[int]

# --- GLContextFlag ---
CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT: Final[int]
CONTEXT_FLAG_DEBUG_BIT: Final[int]
CONTEXT_FLAG_ROBUST_ACCESS_BIT: Final[int]
CONTEXT_CORE_PROFILE_BIT: Final[int]
CONTEXT_COMPATIBILITY_PROFILE_BIT: Final[int]

# --- GLTextureTarget ---
TEXTURE_1D: Final[int]
TEXTURE_2D: Final[int]
TEXTURE_3D: Final[int]
TEXTURE_1D_ARRAY: Final[int]
TEXTURE_2D_ARRAY: Final[int]
TEXTURE_RECTANGLE: Final[int]
TEXTURE_CUBE_MAP: Final[int]
TEXTURE_CUBE_MAP_ARRAY: Final[int]
TEXTURE_2D_MULTISAMPLE: Final[int]
TEXTURE_2D_MULTISAMPLE_ARRAY: Final[int]
TEXTURE_BUFFER: Final[int]
PROXY_TEXTURE_1D: Final[int]
PROXY_TEXTURE_2D: Final[int]
PROXY_TEXTURE_3D: Final[int]
PROXY_TEXTURE_CUBE_MAP: Final[int]

# --- GLTextureCubeMapFace ---
TEXTURE_CUBE_MAP_POSITIVE_X: Final[int]
TEXTURE_CUBE_MAP_NEGATIVE_X: Final[int]
TEXTURE_CUBE_MAP_POSITIVE_Y: Final[int]
TEXTURE_CUBE_MAP_NEGATIVE_Y: Final[int]
TEXTURE_CUBE_MAP_POSITIVE_Z: Final[int]
TEXTURE_CUBE_MAP_NEGATIVE_Z: Final[int]

# --- GLTextureParameter ---
TEXTURE_MIN_FILTER: Final[int]
TEXTURE_MAG_FILTER: Final[int]
TEXTURE_WRAP_S: Final[int]
TEXTURE_WRAP_T: Final[int]
TEXTURE_WRAP_R: Final[int]
TEXTURE_BASE_LEVEL: Final[int]
TEXTURE_MAX_LEVEL: Final[int]
TEXTURE_MIN_LOD: Final[int]
TEXTURE_MAX_LOD: Final[int]
TEXTURE_LOD_BIAS: Final[int]
TEXTURE_COMPARE_MODE: Final[int]
TEXTURE_COMPARE_FUNC: Final[int]
TEXTURE_SWIZZLE_R: Final[int]
TEXTURE_SWIZZLE_G: Final[int]
TEXTURE_SWIZZLE_B: Final[int]
TEXTURE_SWIZZLE_A: Final[int]
TEXTURE_SWIZZLE_RGBA: Final[int]
TEXTURE_BORDER_COLOR: Final[int]
TEXTURE_MAX_ANISOTROPY: Final[int]
DEPTH_STENCIL_TEXTURE_MODE: Final[int]

# --- GLTextureFilter ---
NEAREST: Final[int]
LINEAR: Final[int]
NEAREST_MIPMAP_NEAREST: Final[int]
LINEAR_MIPMAP_NEAREST: Final[int]
NEAREST_MIPMAP_LINEAR: Final[int]
LINEAR_MIPMAP_LINEAR: Final[int]

# --- GLTextureWrapMode ---
REPEAT: Final[int]
CLAMP_TO_EDGE: Final[int]
CLAMP_TO_BORDER: Final[int]
MIRRORED_REPEAT: Final[int]
MIRROR_CLAMP_TO_EDGE: Final[int]

# --- GLTextureCompareMode ---
COMPARE_REF_TO_TEXTURE: Final[int]
TEXTURE_COMPARE_MODE_NONE: Final[int]

# --- GLTextureSwizzle ---
RED_COMPONENT: Final[int]
GREEN: Final[int]
BLUE: Final[int]
ALPHA: Final[int]

# --- GLTextureUnit ---
TEXTURE0: Final[int]
TEXTURE1: Final[int]
TEXTURE2: Final[int]
TEXTURE3: Final[int]
TEXTURE4: Final[int]
TEXTURE5: Final[int]
TEXTURE6: Final[int]
TEXTURE7: Final[int]
TEXTURE8: Final[int]
TEXTURE9: Final[int]
TEXTURE10: Final[int]
TEXTURE11: Final[int]
TEXTURE12: Final[int]
TEXTURE13: Final[int]
TEXTURE14: Final[int]
TEXTURE15: Final[int]
TEXTURE16: Final[int]
TEXTURE17: Final[int]
TEXTURE18: Final[int]
TEXTURE19: Final[int]
TEXTURE20: Final[int]
TEXTURE21: Final[int]
TEXTURE22: Final[int]
TEXTURE23: Final[int]
TEXTURE24: Final[int]
TEXTURE25: Final[int]
TEXTURE26: Final[int]
TEXTURE27: Final[int]
TEXTURE28: Final[int]
TEXTURE29: Final[int]
TEXTURE30: Final[int]
TEXTURE31: Final[int]

# --- GLInternalFormat ---
R8: Final[int]
R8_SNORM: Final[int]
R16: Final[int]
R16_SNORM: Final[int]
RG8: Final[int]
RG8_SNORM: Final[int]
RG16: Final[int]
RG16_SNORM: Final[int]
R3_G3_B2: Final[int]
RGB4: Final[int]
RGB5: Final[int]
RGB8: Final[int]
RGB8_SNORM: Final[int]
RGB10: Final[int]
RGB12: Final[int]
RGB16: Final[int]
RGB16_SNORM: Final[int]
RGBA2: Final[int]
RGBA4: Final[int]
RGB5_A1: Final[int]
RGBA8: Final[int]
RGBA8_SNORM: Final[int]
RGB10_A2: Final[int]
RGB10_A2UI: Final[int]
RGBA12: Final[int]
RGBA16: Final[int]
RGBA16_SNORM: Final[int]
SRGB8: Final[int]
SRGB8_ALPHA8: Final[int]
R16F: Final[int]
RG16F: Final[int]
RGB16F: Final[int]
RGBA16F: Final[int]
R32F: Final[int]
RG32F: Final[int]
RGB32F: Final[int]
RGBA32F: Final[int]
R11F_G11F_B10F: Final[int]
RGB9_E5: Final[int]
R8I: Final[int]
R8UI: Final[int]
R16I: Final[int]
R16UI: Final[int]
R32I: Final[int]
R32UI: Final[int]
RG8I: Final[int]
RG8UI: Final[int]
RG16I: Final[int]
RG16UI: Final[int]
RG32I: Final[int]
RG32UI: Final[int]
RGB8I: Final[int]
RGB8UI: Final[int]
RGB16I: Final[int]
RGB16UI: Final[int]
RGB32I: Final[int]
RGB32UI: Final[int]
RGBA8I: Final[int]
RGBA8UI: Final[int]
RGBA16I: Final[int]
RGBA16UI: Final[int]
RGBA32I: Final[int]
RGBA32UI: Final[int]
DEPTH_COMPONENT16: Final[int]
DEPTH_COMPONENT24: Final[int]
DEPTH_COMPONENT32: Final[int]
DEPTH_COMPONENT32F: Final[int]
DEPTH24_STENCIL8: Final[int]
DEPTH32F_STENCIL8: Final[int]
STENCIL_INDEX1: Final[int]
STENCIL_INDEX4: Final[int]
STENCIL_INDEX8: Final[int]
STENCIL_INDEX16: Final[int]
COMPRESSED_RED: Final[int]
COMPRESSED_RG: Final[int]
COMPRESSED_RGB: Final[int]
COMPRESSED_RGBA: Final[int]
COMPRESSED_SRGB: Final[int]
COMPRESSED_SRGB_ALPHA: Final[int]
COMPRESSED_RED_RGTC1: Final[int]
COMPRESSED_SIGNED_RED_RGTC1: Final[int]
COMPRESSED_RG_RGTC2: Final[int]
COMPRESSED_SIGNED_RG_RGTC2: Final[int]
COMPRESSED_RGBA_BPTC_UNORM: Final[int]
COMPRESSED_SRGB_ALPHA_BPTC_UNORM: Final[int]
COMPRESSED_RGB_BPTC_SIGNED_FLOAT: Final[int]
COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT: Final[int]

# --- GLPixelFormat ---
RED: Final[int]
RG: Final[int]
RGB: Final[int]
RGBA: Final[int]
BGR: Final[int]
BGRA: Final[int]
RED_INTEGER: Final[int]
RG_INTEGER: Final[int]
RGB_INTEGER: Final[int]
RGBA_INTEGER: Final[int]
BGR_INTEGER: Final[int]
BGRA_INTEGER: Final[int]
STENCIL_INDEX: Final[int]
DEPTH_COMPONENT: Final[int]
DEPTH_STENCIL: Final[int]

# --- GLPixelStoreParameter ---
UNPACK_SWAP_BYTES: Final[int]
UNPACK_LSB_FIRST: Final[int]
UNPACK_ROW_LENGTH: Final[int]
UNPACK_SKIP_ROWS: Final[int]
UNPACK_SKIP_PIXELS: Final[int]
UNPACK_ALIGNMENT: Final[int]
UNPACK_IMAGE_HEIGHT: Final[int]
UNPACK_SKIP_IMAGES: Final[int]
PACK_SWAP_BYTES: Final[int]
PACK_LSB_FIRST: Final[int]
PACK_ROW_LENGTH: Final[int]
PACK_SKIP_ROWS: Final[int]
PACK_SKIP_PIXELS: Final[int]
PACK_ALIGNMENT: Final[int]
PACK_IMAGE_HEIGHT: Final[int]
PACK_SKIP_IMAGES: Final[int]

# --- GLBufferTarget ---
ARRAY_BUFFER: Final[int]
ELEMENT_ARRAY_BUFFER: Final[int]
PIXEL_PACK_BUFFER: Final[int]
PIXEL_UNPACK_BUFFER: Final[int]
UNIFORM_BUFFER: Final[int]
TRANSFORM_FEEDBACK_BUFFER: Final[int]
COPY_READ_BUFFER: Final[int]
COPY_WRITE_BUFFER: Final[int]
DRAW_INDIRECT_BUFFER: Final[int]
SHADER_STORAGE_BUFFER: Final[int]
DISPATCH_INDIRECT_BUFFER: Final[int]
QUERY_BUFFER: Final[int]
ATOMIC_COUNTER_BUFFER: Final[int]

# --- GLBufferUsage ---
STREAM_DRAW: Final[int]
STREAM_READ: Final[int]
STREAM_COPY: Final[int]
STATIC_DRAW: Final[int]
STATIC_READ: Final[int]
STATIC_COPY: Final[int]
DYNAMIC_DRAW: Final[int]
DYNAMIC_READ: Final[int]
DYNAMIC_COPY: Final[int]

# --- GLBufferStorageMapMask ---
MAP_READ_BIT: Final[int]
MAP_WRITE_BIT: Final[int]
MAP_INVALIDATE_RANGE_BIT: Final[int]
MAP_INVALIDATE_BUFFER_BIT: Final[int]
MAP_FLUSH_EXPLICIT_BIT: Final[int]
MAP_UNSYNCHRONIZED_BIT: Final[int]
MAP_PERSISTENT_BIT: Final[int]
MAP_COHERENT_BIT: Final[int]
DYNAMIC_STORAGE_BIT: Final[int]
CLIENT_STORAGE_BIT: Final[int]

# --- GLBufferParameter ---
BUFFER_SIZE: Final[int]
BUFFER_USAGE: Final[int]
BUFFER_ACCESS: Final[int]
BUFFER_MAPPED: Final[int]
BUFFER_MAP_POINTER: Final[int]
BUFFER_ACCESS_FLAGS: Final[int]
BUFFER_MAP_LENGTH: Final[int]
BUFFER_MAP_OFFSET: Final[int]
BUFFER_IMMUTABLE_STORAGE: Final[int]
BUFFER_STORAGE_FLAGS: Final[int]

# --- GLFramebufferTarget ---
FRAMEBUFFER: Final[int]
READ_FRAMEBUFFER: Final[int]
DRAW_FRAMEBUFFER: Final[int]

# --- GLRenderbufferTarget ---
RENDERBUFFER: Final[int]

# --- GLFramebufferAttachment ---
COLOR_ATTACHMENT0: Final[int]
COLOR_ATTACHMENT1: Final[int]
COLOR_ATTACHMENT2: Final[int]
COLOR_ATTACHMENT3: Final[int]
COLOR_ATTACHMENT4: Final[int]
COLOR_ATTACHMENT5: Final[int]
COLOR_ATTACHMENT6: Final[int]
COLOR_ATTACHMENT7: Final[int]
COLOR_ATTACHMENT8: Final[int]
COLOR_ATTACHMENT9: Final[int]
COLOR_ATTACHMENT10: Final[int]
COLOR_ATTACHMENT11: Final[int]
COLOR_ATTACHMENT12: Final[int]
COLOR_ATTACHMENT13: Final[int]
COLOR_ATTACHMENT14: Final[int]
COLOR_ATTACHMENT15: Final[int]
DEPTH_ATTACHMENT: Final[int]
STENCIL_ATTACHMENT: Final[int]
DEPTH_STENCIL_ATTACHMENT: Final[int]

# --- GLFramebufferStatus ---
FRAMEBUFFER_COMPLETE: Final[int]
FRAMEBUFFER_INCOMPLETE_ATTACHMENT: Final[int]
FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: Final[int]
FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER: Final[int]
FRAMEBUFFER_INCOMPLETE_READ_BUFFER: Final[int]
FRAMEBUFFER_UNSUPPORTED: Final[int]
FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: Final[int]
FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS: Final[int]
FRAMEBUFFER_DEFAULT: Final[int]
FRAMEBUFFER_UNDEFINED: Final[int]

# --- GLFramebufferAttachmentParameter ---
FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: Final[int]
FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: Final[int]
FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: Final[int]
FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: Final[int]
FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER: Final[int]
FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING: Final[int]
FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: Final[int]
FRAMEBUFFER_ATTACHMENT_RED_SIZE: Final[int]
FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: Final[int]
FRAMEBUFFER_ATTACHMENT_BLUE_SIZE: Final[int]
FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: Final[int]
FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE: Final[int]
FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: Final[int]

# --- GLRenderbufferParameter ---
RENDERBUFFER_WIDTH: Final[int]
RENDERBUFFER_HEIGHT: Final[int]
RENDERBUFFER_INTERNAL_FORMAT: Final[int]
RENDERBUFFER_RED_SIZE: Final[int]
RENDERBUFFER_GREEN_SIZE: Final[int]
RENDERBUFFER_BLUE_SIZE: Final[int]
RENDERBUFFER_ALPHA_SIZE: Final[int]
RENDERBUFFER_DEPTH_SIZE: Final[int]
RENDERBUFFER_STENCIL_SIZE: Final[int]
RENDERBUFFER_SAMPLES: Final[int]

# --- GLShaderType ---
FRAGMENT_SHADER: Final[int]
VERTEX_SHADER: Final[int]
GEOMETRY_SHADER: Final[int]
TESS_EVALUATION_SHADER: Final[int]
TESS_CONTROL_SHADER: Final[int]
COMPUTE_SHADER: Final[int]

# --- GLShaderParameter ---
SHADER_TYPE: Final[int]
DELETE_STATUS: Final[int]
COMPILE_STATUS: Final[int]
INFO_LOG_LENGTH: Final[int]
SHADER_SOURCE_LENGTH: Final[int]

# --- GLProgramParameter ---
LINK_STATUS: Final[int]
VALIDATE_STATUS: Final[int]
ATTACHED_SHADERS: Final[int]
ACTIVE_UNIFORMS: Final[int]
ACTIVE_UNIFORM_MAX_LENGTH: Final[int]
ACTIVE_ATTRIBUTES: Final[int]
ACTIVE_ATTRIBUTE_MAX_LENGTH: Final[int]

# --- GLUniformType ---
FLOAT_VEC2: Final[int]
FLOAT_VEC3: Final[int]
FLOAT_VEC4: Final[int]
DOUBLE_VEC2: Final[int]
DOUBLE_VEC3: Final[int]
DOUBLE_VEC4: Final[int]
INT_VEC2: Final[int]
INT_VEC3: Final[int]
INT_VEC4: Final[int]
UNSIGNED_INT_VEC2: Final[int]
UNSIGNED_INT_VEC3: Final[int]
UNSIGNED_INT_VEC4: Final[int]
BOOL: Final[int]
BOOL_VEC2: Final[int]
BOOL_VEC3: Final[int]
BOOL_VEC4: Final[int]
FLOAT_MAT2: Final[int]
FLOAT_MAT3: Final[int]
FLOAT_MAT4: Final[int]
FLOAT_MAT2x3: Final[int]
FLOAT_MAT2x4: Final[int]
FLOAT_MAT3x2: Final[int]
FLOAT_MAT3x4: Final[int]
FLOAT_MAT4x2: Final[int]
FLOAT_MAT4x3: Final[int]
DOUBLE_MAT2: Final[int]
DOUBLE_MAT3: Final[int]
DOUBLE_MAT4: Final[int]
SAMPLER_1D: Final[int]
SAMPLER_2D: Final[int]
SAMPLER_3D: Final[int]
SAMPLER_CUBE: Final[int]
SAMPLER_1D_SHADOW: Final[int]
SAMPLER_2D_SHADOW: Final[int]

# --- GLProgramInterface ---
UNIFORM: Final[int]
UNIFORM_BLOCK: Final[int]
PROGRAM_INPUT: Final[int]
PROGRAM_OUTPUT: Final[int]
BUFFER_VARIABLE: Final[int]
SHADER_STORAGE_BLOCK: Final[int]
VERTEX_SUBROUTINE: Final[int]
TESS_CONTROL_SUBROUTINE: Final[int]
TESS_EVALUATION_SUBROUTINE: Final[int]
GEOMETRY_SUBROUTINE: Final[int]
FRAGMENT_SUBROUTINE: Final[int]
COMPUTE_SUBROUTINE: Final[int]
VERTEX_SUBROUTINE_UNIFORM: Final[int]
TESS_CONTROL_SUBROUTINE_UNIFORM: Final[int]
TESS_EVALUATION_SUBROUTINE_UNIFORM: Final[int]
GEOMETRY_SUBROUTINE_UNIFORM: Final[int]
FRAGMENT_SUBROUTINE_UNIFORM: Final[int]
COMPUTE_SUBROUTINE_UNIFORM: Final[int]
TRANSFORM_FEEDBACK_VARYING: Final[int]

# --- GLProgramResourceProperty ---
ACTIVE_RESOURCES: Final[int]
MAX_NAME_LENGTH: Final[int]
MAX_NUM_ACTIVE_VARIABLES: Final[int]
NAME_LENGTH: Final[int]
TYPE: Final[int]
ARRAY_SIZE: Final[int]
OFFSET: Final[int]
BLOCK_INDEX: Final[int]
ARRAY_STRIDE: Final[int]
MATRIX_STRIDE: Final[int]
IS_ROW_MAJOR: Final[int]
ATOMIC_COUNTER_BUFFER_INDEX: Final[int]
BUFFER_BINDING: Final[int]
BUFFER_DATA_SIZE: Final[int]
NUM_ACTIVE_VARIABLES: Final[int]
ACTIVE_VARIABLES: Final[int]
REFERENCED_BY_VERTEX_SHADER: Final[int]
REFERENCED_BY_TESS_CONTROL_SHADER: Final[int]
REFERENCED_BY_TESS_EVALUATION_SHADER: Final[int]
REFERENCED_BY_GEOMETRY_SHADER: Final[int]
REFERENCED_BY_FRAGMENT_SHADER: Final[int]
REFERENCED_BY_COMPUTE_SHADER: Final[int]
TOP_LEVEL_ARRAY_SIZE: Final[int]
TOP_LEVEL_ARRAY_STRIDE: Final[int]
LOCATION: Final[int]
LOCATION_INDEX: Final[int]
IS_PER_PATCH: Final[int]

# --- GLVertexAttribParameter ---
VERTEX_ATTRIB_ARRAY_ENABLED: Final[int]
VERTEX_ATTRIB_ARRAY_SIZE: Final[int]
VERTEX_ATTRIB_ARRAY_STRIDE: Final[int]
VERTEX_ATTRIB_ARRAY_TYPE: Final[int]
VERTEX_ATTRIB_ARRAY_NORMALIZED: Final[int]
VERTEX_ATTRIB_ARRAY_POINTER: Final[int]
VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: Final[int]
VERTEX_ATTRIB_ARRAY_INTEGER: Final[int]
VERTEX_ATTRIB_ARRAY_DIVISOR: Final[int]
VERTEX_ATTRIB_ARRAY_LONG: Final[int]
VERTEX_ATTRIB_BINDING: Final[int]
VERTEX_ATTRIB_RELATIVE_OFFSET: Final[int]
VERTEX_BINDING_DIVISOR: Final[int]
VERTEX_BINDING_OFFSET: Final[int]
VERTEX_BINDING_STRIDE: Final[int]
VERTEX_BINDING_BUFFER: Final[int]

# --- GLImageAccess ---
READ_ONLY: Final[int]
WRITE_ONLY: Final[int]
READ_WRITE: Final[int]

# --- GLMemoryBarrierMask ---
VERTEX_ATTRIB_ARRAY_BARRIER_BIT: Final[int]
ELEMENT_ARRAY_BARRIER_BIT: Final[int]
UNIFORM_BARRIER_BIT: Final[int]
TEXTURE_FETCH_BARRIER_BIT: Final[int]
SHADER_IMAGE_ACCESS_BARRIER_BIT: Final[int]
COMMAND_BARRIER_BIT: Final[int]
PIXEL_BUFFER_BARRIER_BIT: Final[int]
TEXTURE_UPDATE_BARRIER_BIT: Final[int]
BUFFER_UPDATE_BARRIER_BIT: Final[int]
FRAMEBUFFER_BARRIER_BIT: Final[int]
TRANSFORM_FEEDBACK_BARRIER_BIT: Final[int]
ATOMIC_COUNTER_BARRIER_BIT: Final[int]
SHADER_STORAGE_BARRIER_BIT: Final[int]
CLIENT_MAPPED_BUFFER_BARRIER_BIT: Final[int]
QUERY_BUFFER_BARRIER_BIT: Final[int]
ALL_BARRIER_BITS: Final[int]

# --- GLSyncStatus ---
ALREADY_SIGNALED: Final[int]
TIMEOUT_EXPIRED: Final[int]
CONDITION_SATISFIED: Final[int]
WAIT_FAILED: Final[int]

# --- GLSyncMask ---
SYNC_FLUSH_COMMANDS_BIT: Final[int]

# --- GLSyncParameter ---
SYNC_GPU_COMMANDS_COMPLETE: Final[int]
SYNC_STATUS: Final[int]
SYNC_CONDITION: Final[int]
SYNC_FLAGS: Final[int]
SYNC_FENCE: Final[int]
OBJECT_TYPE: Final[int]

# --- GLQueryTarget ---
SAMPLES_PASSED: Final[int]
ANY_SAMPLES_PASSED: Final[int]
ANY_SAMPLES_PASSED_CONSERVATIVE: Final[int]
PRIMITIVES_GENERATED: Final[int]
TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: Final[int]
TIME_ELAPSED: Final[int]
TIMESTAMP: Final[int]

# --- GLQueryParameter ---
QUERY_RESULT: Final[int]
QUERY_RESULT_AVAILABLE: Final[int]
QUERY_RESULT_NO_WAIT: Final[int]

# --- GLTransformFeedbackMode ---
INTERLEAVED_ATTRIBS: Final[int]
SEPARATE_ATTRIBS: Final[int]
TRANSFORM_FEEDBACK: Final[int]

# --- GLPatchParameter ---
PATCH_VERTICES: Final[int]
PATCH_DEFAULT_INNER_LEVEL: Final[int]
PATCH_DEFAULT_OUTER_LEVEL: Final[int]
TESS_GEN_MODE: Final[int]
TESS_GEN_SPACING: Final[int]
TESS_GEN_VERTEX_ORDER: Final[int]
TESS_GEN_POINT_MODE: Final[int]

# --- GLProvokingVertexMode ---
FIRST_VERTEX_CONVENTION: Final[int]
LAST_VERTEX_CONVENTION: Final[int]
PROVOKING_VERTEX: Final[int]

# --- GLLogicOp ---
CLEAR: Final[int]
AND: Final[int]
AND_REVERSE: Final[int]
COPY: Final[int]
AND_INVERTED: Final[int]
NOOP: Final[int]
XOR: Final[int]
OR: Final[int]
NOR: Final[int]
EQUIV: Final[int]
LOGIC_INVERT: Final[int]
OR_REVERSE: Final[int]
COPY_INVERTED: Final[int]
OR_INVERTED: Final[int]
NAND: Final[int]
SET: Final[int]

# --- GLAtomicCounterParameter ---
ATOMIC_COUNTER_BUFFER_BINDING: Final[int]
ATOMIC_COUNTER_BUFFER_DATA_SIZE: Final[int]
ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS: Final[int]
UNSIGNED_INT_ATOMIC_COUNTER: Final[int]

# --- GLDebugSource ---
DEBUG_SOURCE_API: Final[int]
DEBUG_SOURCE_WINDOW_SYSTEM: Final[int]
DEBUG_SOURCE_SHADER_COMPILER: Final[int]
DEBUG_SOURCE_THIRD_PARTY: Final[int]
DEBUG_SOURCE_APPLICATION: Final[int]
DEBUG_SOURCE_OTHER: Final[int]

# --- GLDebugType ---
DEBUG_TYPE_ERROR: Final[int]
DEBUG_TYPE_DEPRECATED_BEHAVIOR: Final[int]
DEBUG_TYPE_UNDEFINED_BEHAVIOR: Final[int]
DEBUG_TYPE_PORTABILITY: Final[int]
DEBUG_TYPE_PERFORMANCE: Final[int]
DEBUG_TYPE_OTHER: Final[int]
DEBUG_TYPE_MARKER: Final[int]
DEBUG_TYPE_PUSH_GROUP: Final[int]
DEBUG_TYPE_POP_GROUP: Final[int]

# --- GLDebugSeverity ---
DEBUG_SEVERITY_HIGH: Final[int]
DEBUG_SEVERITY_MEDIUM: Final[int]
DEBUG_SEVERITY_LOW: Final[int]
DEBUG_SEVERITY_NOTIFICATION: Final[int]

# --- GLDebugParameter ---
DEBUG_LOGGED_MESSAGES: Final[int]
DEBUG_NEXT_LOGGED_MESSAGE_LENGTH: Final[int]
DEBUG_GROUP_STACK_DEPTH: Final[int]

# --- GLObjectIdentifier ---
BUFFER_OBJECT: Final[int]
SHADER_OBJECT: Final[int]
PROGRAM_OBJECT: Final[int]
VERTEX_ARRAY_OBJECT: Final[int]
QUERY_OBJECT: Final[int]
PROGRAM_PIPELINE_OBJECT: Final[int]
SAMPLER_OBJECT: Final[int]

# --- GLDrawBuffer ---
DRAW_BUFFER0: Final[int]
DRAW_BUFFER1: Final[int]
DRAW_BUFFER2: Final[int]
DRAW_BUFFER3: Final[int]
DRAW_BUFFER4: Final[int]
DRAW_BUFFER5: Final[int]
DRAW_BUFFER6: Final[int]
DRAW_BUFFER7: Final[int]
DRAW_BUFFER8: Final[int]
DRAW_BUFFER9: Final[int]
DRAW_BUFFER10: Final[int]
DRAW_BUFFER11: Final[int]
DRAW_BUFFER12: Final[int]
DRAW_BUFFER13: Final[int]
DRAW_BUFFER14: Final[int]
DRAW_BUFFER15: Final[int]
BACK_LEFT: Final[int]
BACK_RIGHT: Final[int]
FRONT_LEFT: Final[int]
FRONT_RIGHT: Final[int]
LEFT: Final[int]
RIGHT: Final[int]
NONE: Final[int]

# --- UniformFunction ---
UF_1I: Final[int]
UF_2I: Final[int]
UF_3I: Final[int]
UF_4I: Final[int]
UF_1B: Final[int]
UF_2B: Final[int]
UF_3B: Final[int]
UF_4B: Final[int]
UF_1U: Final[int]
UF_2U: Final[int]
UF_3U: Final[int]
UF_4U: Final[int]
UF_1F: Final[int]
UF_2F: Final[int]
UF_3F: Final[int]
UF_4F: Final[int]
UF_MAT2: Final[int]
UF_MAT2x3: Final[int]
UF_MAT2x4: Final[int]
UF_MAT3x2: Final[int]
UF_MAT3: Final[int]
UF_MAT3x4: Final[int]
UF_MAT4x2: Final[int]
UF_MAT4x3: Final[int]
UF_MAT4: Final[int]
UF_MAT2_RM: Final[int]
UF_MAT3_RM: Final[int]
UF_MAT4_RM: Final[int]

# --- ImageFormatTupleIndex ---
IF_INTERNAL_FORMAT: Final[int]
IF_FORMAT: Final[int]
IF_TYPE: Final[int]
IF_BUFFER: Final[int]
IF_COMPONENTS: Final[int]
IF_PIXEL_SIZE: Final[int]
IF_COLOR: Final[int]
IF_FLAGS: Final[int]
IF_CLEAR_TYPE: Final[int]

__all__ = [
    "FALSE",
    "TRUE",
    "INVALID_INDEX",
    "TIMEOUT_IGNORED",
    "INVALID_ENUM_VALUE",
    "PERSISTENT_WRITE_FLAGS",
    "SPEC_MIN_MAP_BUFFER_ALIGNMENT",
    "SPEC_MIN_TEXEL_OFFSET",
    "SPEC_MAX_TEXEL_OFFSET",
    "SPEC_MIN_UBO_BINDINGS",
    "SPEC_MIN_TEXTURE_UNITS",
    "SPEC_MIN_COMBINED_TEXTURE_UNITS",
    "SPEC_MIN_COLOR_ATTACHMENTS",
    "DONT_CARE",
    "BYTE",
    "UNSIGNED_BYTE",
    "SHORT",
    "UNSIGNED_SHORT",
    "INT",
    "UNSIGNED_INT",
    "FLOAT",
    "DOUBLE",
    "HALF_FLOAT",
    "FIXED",
    "INT_2_10_10_10_REV",
    "UNSIGNED_INT_2_10_10_10_REV",
    "UNSIGNED_INT_10F_11F_11F_REV",
    "UNSIGNED_BYTE_3_3_2",
    "UNSIGNED_SHORT_4_4_4_4",
    "UNSIGNED_SHORT_5_5_5_1",
    "UNSIGNED_INT_8_8_8_8",
    "UNSIGNED_INT_10_10_10_2",
    "UNSIGNED_BYTE_2_3_3_REV",
    "UNSIGNED_SHORT_5_6_5",
    "UNSIGNED_SHORT_5_6_5_REV",
    "UNSIGNED_SHORT_4_4_4_4_REV",
    "UNSIGNED_SHORT_1_5_5_5_REV",
    "UNSIGNED_INT_8_8_8_8_REV",
    "UNSIGNED_INT_24_8",
    "FLOAT_32_UNSIGNED_INT_24_8_REV",
    "POINTS",
    "LINES",
    "LINE_LOOP",
    "LINE_STRIP",
    "TRIANGLES",
    "TRIANGLE_STRIP",
    "TRIANGLE_FAN",
    "LINES_ADJACENCY",
    "LINE_STRIP_ADJACENCY",
    "TRIANGLES_ADJACENCY",
    "TRIANGLE_STRIP_ADJACENCY",
    "PATCHES",
    "ZERO",
    "ONE",
    "SRC_COLOR",
    "ONE_MINUS_SRC_COLOR",
    "SRC_ALPHA",
    "ONE_MINUS_SRC_ALPHA",
    "DST_ALPHA",
    "ONE_MINUS_DST_ALPHA",
    "DST_COLOR",
    "ONE_MINUS_DST_COLOR",
    "SRC_ALPHA_SATURATE",
    "CONSTANT_COLOR",
    "ONE_MINUS_CONSTANT_COLOR",
    "CONSTANT_ALPHA",
    "ONE_MINUS_CONSTANT_ALPHA",
    "SRC1_COLOR",
    "ONE_MINUS_SRC1_COLOR",
    "SRC1_ALPHA",
    "ONE_MINUS_SRC1_ALPHA",
    "FUNC_ADD",
    "FUNC_SUBTRACT",
    "FUNC_REVERSE_SUBTRACT",
    "MIN",
    "MAX",
    "DEPTH_BUFFER_BIT",
    "STENCIL_BUFFER_BIT",
    "COLOR_BUFFER_BIT",
    "COLOR",
    "DEPTH",
    "STENCIL",
    "NO_ERROR",
    "INVALID_ENUM",
    "INVALID_VALUE",
    "INVALID_OPERATION",
    "STACK_OVERFLOW",
    "STACK_UNDERFLOW",
    "OUT_OF_MEMORY",
    "INVALID_FRAMEBUFFER_OPERATION",
    "CONTEXT_LOST",
    "VENDOR",
    "RENDERER",
    "VERSION",
    "EXTENSIONS",
    "SHADING_LANGUAGE_VERSION",
    "CW",
    "CCW",
    "FRONT",
    "BACK",
    "FRONT_AND_BACK",
    "POINT",
    "LINE",
    "FILL",
    "NEVER",
    "LESS",
    "EQUAL",
    "LEQUAL",
    "GREATER",
    "NOTEQUAL",
    "GEQUAL",
    "ALWAYS",
    "KEEP",
    "REPLACE",
    "INCR",
    "DECR",
    "INVERT",
    "INCR_WRAP",
    "DECR_WRAP",
    "CULL_FACE",
    "DEPTH_TEST",
    "STENCIL_TEST",
    "BLEND",
    "SCISSOR_TEST",
    "COLOR_LOGIC_OP",
    "DITHER",
    "LINE_SMOOTH",
    "POLYGON_SMOOTH",
    "POLYGON_OFFSET_POINT",
    "POLYGON_OFFSET_LINE",
    "POLYGON_OFFSET_FILL",
    "MULTISAMPLE",
    "SAMPLE_ALPHA_TO_COVERAGE",
    "SAMPLE_ALPHA_TO_ONE",
    "SAMPLE_COVERAGE",
    "SAMPLE_SHADING",
    "SAMPLE_MASK",
    "PRIMITIVE_RESTART",
    "PRIMITIVE_RESTART_FIXED_INDEX",
    "RASTERIZER_DISCARD",
    "FRAMEBUFFER_SRGB",
    "DEPTH_CLAMP",
    "TEXTURE_CUBE_MAP_SEAMLESS",
    "PROGRAM_POINT_SIZE",
    "DEBUG_OUTPUT",
    "DEBUG_OUTPUT_SYNCHRONOUS",
    "VIEWPORT",
    "DEPTH_RANGE",
    "DEPTH_WRITEMASK",
    "DEPTH_CLEAR_VALUE",
    "DEPTH_FUNC",
    "STENCIL_CLEAR_VALUE",
    "STENCIL_FUNC",
    "STENCIL_VALUE_MASK",
    "STENCIL_FAIL",
    "STENCIL_PASS_DEPTH_FAIL",
    "STENCIL_PASS_DEPTH_PASS",
    "STENCIL_REF",
    "STENCIL_WRITEMASK",
    "SCISSOR_BOX",
    "COLOR_CLEAR_VALUE",
    "COLOR_WRITEMASK",
    "MAX_TEXTURE_SIZE",
    "MAX_VIEWPORT_DIMS",
    "SUBPIXEL_BITS",
    "MAX_ELEMENTS_VERTICES",
    "MAX_ELEMENTS_INDICES",
    "MAX_3D_TEXTURE_SIZE",
    "MAX_DRAW_BUFFERS",
    "MAX_VERTEX_ATTRIBS",
    "MAX_TEXTURE_IMAGE_UNITS",
    "MAX_FRAGMENT_UNIFORM_COMPONENTS",
    "MAX_VERTEX_UNIFORM_COMPONENTS",
    "MAX_VARYING_FLOATS",
    "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
    "MAX_COMBINED_TEXTURE_IMAGE_UNITS",
    "MAX_RENDERBUFFER_SIZE",
    "MAX_COLOR_ATTACHMENTS",
    "MAX_SAMPLES",
    "MAX_RECTANGLE_TEXTURE_SIZE",
    "MAX_TEXTURE_LOD_BIAS",
    "MAX_CUBE_MAP_TEXTURE_SIZE",
    "MAX_ARRAY_TEXTURE_LAYERS",
    "MAX_TEXTURE_BUFFER_SIZE",
    "MAX_UNIFORM_BUFFER_BINDINGS",
    "MAX_UNIFORM_BLOCK_SIZE",
    "MAX_COMBINED_UNIFORM_BLOCKS",
    "MAX_VERTEX_UNIFORM_BLOCKS",
    "MAX_GEOMETRY_UNIFORM_BLOCKS",
    "MAX_FRAGMENT_UNIFORM_BLOCKS",
    "MAX_SHADER_STORAGE_BUFFER_BINDINGS",
    "MAX_SHADER_STORAGE_BLOCK_SIZE",
    "MAX_COMPUTE_SHADER_STORAGE_BLOCKS",
    "MAX_COMPUTE_UNIFORM_BLOCKS",
    "MAX_COMPUTE_TEXTURE_IMAGE_UNITS",
    "MAX_COMPUTE_IMAGE_UNIFORMS",
    "MAX_COMPUTE_WORK_GROUP_SIZE",
    "MAX_COMPUTE_WORK_GROUP_INVOCATIONS",
    "MAX_IMAGE_UNITS",
    "MAX_VERTEX_IMAGE_UNIFORMS",
    "MAX_FRAGMENT_IMAGE_UNIFORMS",
    "MAX_COMBINED_IMAGE_UNIFORMS",
    "MAX_GEOMETRY_IMAGE_UNIFORMS",
    "MAX_TESS_CONTROL_IMAGE_UNIFORMS",
    "MAX_TESS_EVALUATION_IMAGE_UNIFORMS",
    "MAX_VERTEX_SHADER_STORAGE_BLOCKS",
    "MAX_FRAGMENT_SHADER_STORAGE_BLOCKS",
    "MAX_GEOMETRY_SHADER_STORAGE_BLOCKS",
    "MAX_VERTEX_ATOMIC_COUNTERS",
    "MAX_FRAGMENT_ATOMIC_COUNTERS",
    "MAX_COMBINED_ATOMIC_COUNTERS",
    "MAX_ATOMIC_COUNTER_BUFFER_SIZE",
    "MAX_VERTEX_ATTRIB_RELATIVE_OFFSET",
    "MAX_VERTEX_ATTRIB_BINDINGS",
    "MAX_VERTEX_ATTRIB_STRIDE",
    "MAX_DEBUG_MESSAGE_LENGTH",
    "MAX_DEBUG_LOGGED_MESSAGES",
    "MAX_DEBUG_GROUP_STACK_DEPTH",
    "MAX_LABEL_LENGTH",
    "NUM_EXTENSIONS",
    "MAJOR_VERSION",
    "MINOR_VERSION",
    "CONTEXT_FLAGS",
    "CONTEXT_PROFILE_MASK",
    "CURRENT_PROGRAM",
    "DRAW_INDIRECT_BUFFER_BINDING",
    "ACTIVE_ATOMIC_COUNTER_BUFFERS",
    "CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT",
    "CONTEXT_FLAG_DEBUG_BIT",
    "CONTEXT_FLAG_ROBUST_ACCESS_BIT",
    "CONTEXT_CORE_PROFILE_BIT",
    "CONTEXT_COMPATIBILITY_PROFILE_BIT",
    "TEXTURE_1D",
    "TEXTURE_2D",
    "TEXTURE_3D",
    "TEXTURE_1D_ARRAY",
    "TEXTURE_2D_ARRAY",
    "TEXTURE_RECTANGLE",
    "TEXTURE_CUBE_MAP",
    "TEXTURE_CUBE_MAP_ARRAY",
    "TEXTURE_2D_MULTISAMPLE",
    "TEXTURE_2D_MULTISAMPLE_ARRAY",
    "TEXTURE_BUFFER",
    "PROXY_TEXTURE_1D",
    "PROXY_TEXTURE_2D",
    "PROXY_TEXTURE_3D",
    "PROXY_TEXTURE_CUBE_MAP",
    "TEXTURE_CUBE_MAP_POSITIVE_X",
    "TEXTURE_CUBE_MAP_NEGATIVE_X",
    "TEXTURE_CUBE_MAP_POSITIVE_Y",
    "TEXTURE_CUBE_MAP_NEGATIVE_Y",
    "TEXTURE_CUBE_MAP_POSITIVE_Z",
    "TEXTURE_CUBE_MAP_NEGATIVE_Z",
    "TEXTURE_MIN_FILTER",
    "TEXTURE_MAG_FILTER",
    "TEXTURE_WRAP_S",
    "TEXTURE_WRAP_T",
    "TEXTURE_WRAP_R",
    "TEXTURE_BASE_LEVEL",
    "TEXTURE_MAX_LEVEL",
    "TEXTURE_MIN_LOD",
    "TEXTURE_MAX_LOD",
    "TEXTURE_LOD_BIAS",
    "TEXTURE_COMPARE_MODE",
    "TEXTURE_COMPARE_FUNC",
    "TEXTURE_SWIZZLE_R",
    "TEXTURE_SWIZZLE_G",
    "TEXTURE_SWIZZLE_B",
    "TEXTURE_SWIZZLE_A",
    "TEXTURE_SWIZZLE_RGBA",
    "TEXTURE_BORDER_COLOR",
    "TEXTURE_MAX_ANISOTROPY",
    "DEPTH_STENCIL_TEXTURE_MODE",
    "NEAREST",
    "LINEAR",
    "NEAREST_MIPMAP_NEAREST",
    "LINEAR_MIPMAP_NEAREST",
    "NEAREST_MIPMAP_LINEAR",
    "LINEAR_MIPMAP_LINEAR",
    "REPEAT",
    "CLAMP_TO_EDGE",
    "CLAMP_TO_BORDER",
    "MIRRORED_REPEAT",
    "MIRROR_CLAMP_TO_EDGE",
    "COMPARE_REF_TO_TEXTURE",
    "TEXTURE_COMPARE_MODE_NONE",
    "RED_COMPONENT",
    "GREEN",
    "BLUE",
    "ALPHA",
    "TEXTURE0",
    "TEXTURE1",
    "TEXTURE2",
    "TEXTURE3",
    "TEXTURE4",
    "TEXTURE5",
    "TEXTURE6",
    "TEXTURE7",
    "TEXTURE8",
    "TEXTURE9",
    "TEXTURE10",
    "TEXTURE11",
    "TEXTURE12",
    "TEXTURE13",
    "TEXTURE14",
    "TEXTURE15",
    "TEXTURE16",
    "TEXTURE17",
    "TEXTURE18",
    "TEXTURE19",
    "TEXTURE20",
    "TEXTURE21",
    "TEXTURE22",
    "TEXTURE23",
    "TEXTURE24",
    "TEXTURE25",
    "TEXTURE26",
    "TEXTURE27",
    "TEXTURE28",
    "TEXTURE29",
    "TEXTURE30",
    "TEXTURE31",
    "R8",
    "R8_SNORM",
    "R16",
    "R16_SNORM",
    "RG8",
    "RG8_SNORM",
    "RG16",
    "RG16_SNORM",
    "R3_G3_B2",
    "RGB4",
    "RGB5",
    "RGB8",
    "RGB8_SNORM",
    "RGB10",
    "RGB12",
    "RGB16",
    "RGB16_SNORM",
    "RGBA2",
    "RGBA4",
    "RGB5_A1",
    "RGBA8",
    "RGBA8_SNORM",
    "RGB10_A2",
    "RGB10_A2UI",
    "RGBA12",
    "RGBA16",
    "RGBA16_SNORM",
    "SRGB8",
    "SRGB8_ALPHA8",
    "R16F",
    "RG16F",
    "RGB16F",
    "RGBA16F",
    "R32F",
    "RG32F",
    "RGB32F",
    "RGBA32F",
    "R11F_G11F_B10F",
    "RGB9_E5",
    "R8I",
    "R8UI",
    "R16I",
    "R16UI",
    "R32I",
    "R32UI",
    "RG8I",
    "RG8UI",
    "RG16I",
    "RG16UI",
    "RG32I",
    "RG32UI",
    "RGB8I",
    "RGB8UI",
    "RGB16I",
    "RGB16UI",
    "RGB32I",
    "RGB32UI",
    "RGBA8I",
    "RGBA8UI",
    "RGBA16I",
    "RGBA16UI",
    "RGBA32I",
    "RGBA32UI",
    "DEPTH_COMPONENT16",
    "DEPTH_COMPONENT24",
    "DEPTH_COMPONENT32",
    "DEPTH_COMPONENT32F",
    "DEPTH24_STENCIL8",
    "DEPTH32F_STENCIL8",
    "STENCIL_INDEX1",
    "STENCIL_INDEX4",
    "STENCIL_INDEX8",
    "STENCIL_INDEX16",
    "COMPRESSED_RED",
    "COMPRESSED_RG",
    "COMPRESSED_RGB",
    "COMPRESSED_RGBA",
    "COMPRESSED_SRGB",
    "COMPRESSED_SRGB_ALPHA",
    "COMPRESSED_RED_RGTC1",
    "COMPRESSED_SIGNED_RED_RGTC1",
    "COMPRESSED_RG_RGTC2",
    "COMPRESSED_SIGNED_RG_RGTC2",
    "COMPRESSED_RGBA_BPTC_UNORM",
    "COMPRESSED_SRGB_ALPHA_BPTC_UNORM",
    "COMPRESSED_RGB_BPTC_SIGNED_FLOAT",
    "COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT",
    "RED",
    "RG",
    "RGB",
    "RGBA",
    "BGR",
    "BGRA",
    "RED_INTEGER",
    "RG_INTEGER",
    "RGB_INTEGER",
    "RGBA_INTEGER",
    "BGR_INTEGER",
    "BGRA_INTEGER",
    "STENCIL_INDEX",
    "DEPTH_COMPONENT",
    "DEPTH_STENCIL",
    "UNPACK_SWAP_BYTES",
    "UNPACK_LSB_FIRST",
    "UNPACK_ROW_LENGTH",
    "UNPACK_SKIP_ROWS",
    "UNPACK_SKIP_PIXELS",
    "UNPACK_ALIGNMENT",
    "UNPACK_IMAGE_HEIGHT",
    "UNPACK_SKIP_IMAGES",
    "PACK_SWAP_BYTES",
    "PACK_LSB_FIRST",
    "PACK_ROW_LENGTH",
    "PACK_SKIP_ROWS",
    "PACK_SKIP_PIXELS",
    "PACK_ALIGNMENT",
    "PACK_IMAGE_HEIGHT",
    "PACK_SKIP_IMAGES",
    "ARRAY_BUFFER",
    "ELEMENT_ARRAY_BUFFER",
    "PIXEL_PACK_BUFFER",
    "PIXEL_UNPACK_BUFFER",
    "UNIFORM_BUFFER",
    "TRANSFORM_FEEDBACK_BUFFER",
    "COPY_READ_BUFFER",
    "COPY_WRITE_BUFFER",
    "DRAW_INDIRECT_BUFFER",
    "SHADER_STORAGE_BUFFER",
    "DISPATCH_INDIRECT_BUFFER",
    "QUERY_BUFFER",
    "ATOMIC_COUNTER_BUFFER",
    "STREAM_DRAW",
    "STREAM_READ",
    "STREAM_COPY",
    "STATIC_DRAW",
    "STATIC_READ",
    "STATIC_COPY",
    "DYNAMIC_DRAW",
    "DYNAMIC_READ",
    "DYNAMIC_COPY",
    "MAP_READ_BIT",
    "MAP_WRITE_BIT",
    "MAP_INVALIDATE_RANGE_BIT",
    "MAP_INVALIDATE_BUFFER_BIT",
    "MAP_FLUSH_EXPLICIT_BIT",
    "MAP_UNSYNCHRONIZED_BIT",
    "MAP_PERSISTENT_BIT",
    "MAP_COHERENT_BIT",
    "DYNAMIC_STORAGE_BIT",
    "CLIENT_STORAGE_BIT",
    "BUFFER_SIZE",
    "BUFFER_USAGE",
    "BUFFER_ACCESS",
    "BUFFER_MAPPED",
    "BUFFER_MAP_POINTER",
    "BUFFER_ACCESS_FLAGS",
    "BUFFER_MAP_LENGTH",
    "BUFFER_MAP_OFFSET",
    "BUFFER_IMMUTABLE_STORAGE",
    "BUFFER_STORAGE_FLAGS",
    "FRAMEBUFFER",
    "READ_FRAMEBUFFER",
    "DRAW_FRAMEBUFFER",
    "RENDERBUFFER",
    "COLOR_ATTACHMENT0",
    "COLOR_ATTACHMENT1",
    "COLOR_ATTACHMENT2",
    "COLOR_ATTACHMENT3",
    "COLOR_ATTACHMENT4",
    "COLOR_ATTACHMENT5",
    "COLOR_ATTACHMENT6",
    "COLOR_ATTACHMENT7",
    "COLOR_ATTACHMENT8",
    "COLOR_ATTACHMENT9",
    "COLOR_ATTACHMENT10",
    "COLOR_ATTACHMENT11",
    "COLOR_ATTACHMENT12",
    "COLOR_ATTACHMENT13",
    "COLOR_ATTACHMENT14",
    "COLOR_ATTACHMENT15",
    "DEPTH_ATTACHMENT",
    "STENCIL_ATTACHMENT",
    "DEPTH_STENCIL_ATTACHMENT",
    "FRAMEBUFFER_COMPLETE",
    "FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
    "FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
    "FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",
    "FRAMEBUFFER_INCOMPLETE_READ_BUFFER",
    "FRAMEBUFFER_UNSUPPORTED",
    "FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
    "FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS",
    "FRAMEBUFFER_DEFAULT",
    "FRAMEBUFFER_UNDEFINED",
    "FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE",
    "FRAMEBUFFER_ATTACHMENT_OBJECT_NAME",
    "FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL",
    "FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE",
    "FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER",
    "FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING",
    "FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE",
    "FRAMEBUFFER_ATTACHMENT_RED_SIZE",
    "FRAMEBUFFER_ATTACHMENT_GREEN_SIZE",
    "FRAMEBUFFER_ATTACHMENT_BLUE_SIZE",
    "FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE",
    "FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE",
    "FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE",
    "RENDERBUFFER_WIDTH",
    "RENDERBUFFER_HEIGHT",
    "RENDERBUFFER_INTERNAL_FORMAT",
    "RENDERBUFFER_RED_SIZE",
    "RENDERBUFFER_GREEN_SIZE",
    "RENDERBUFFER_BLUE_SIZE",
    "RENDERBUFFER_ALPHA_SIZE",
    "RENDERBUFFER_DEPTH_SIZE",
    "RENDERBUFFER_STENCIL_SIZE",
    "RENDERBUFFER_SAMPLES",
    "FRAGMENT_SHADER",
    "VERTEX_SHADER",
    "GEOMETRY_SHADER",
    "TESS_EVALUATION_SHADER",
    "TESS_CONTROL_SHADER",
    "COMPUTE_SHADER",
    "SHADER_TYPE",
    "DELETE_STATUS",
    "COMPILE_STATUS",
    "INFO_LOG_LENGTH",
    "SHADER_SOURCE_LENGTH",
    "LINK_STATUS",
    "VALIDATE_STATUS",
    "ATTACHED_SHADERS",
    "ACTIVE_UNIFORMS",
    "ACTIVE_UNIFORM_MAX_LENGTH",
    "ACTIVE_ATTRIBUTES",
    "ACTIVE_ATTRIBUTE_MAX_LENGTH",
    "FLOAT_VEC2",
    "FLOAT_VEC3",
    "FLOAT_VEC4",
    "DOUBLE_VEC2",
    "DOUBLE_VEC3",
    "DOUBLE_VEC4",
    "INT_VEC2",
    "INT_VEC3",
    "INT_VEC4",
    "UNSIGNED_INT_VEC2",
    "UNSIGNED_INT_VEC3",
    "UNSIGNED_INT_VEC4",
    "BOOL",
    "BOOL_VEC2",
    "BOOL_VEC3",
    "BOOL_VEC4",
    "FLOAT_MAT2",
    "FLOAT_MAT3",
    "FLOAT_MAT4",
    "FLOAT_MAT2x3",
    "FLOAT_MAT2x4",
    "FLOAT_MAT3x2",
    "FLOAT_MAT3x4",
    "FLOAT_MAT4x2",
    "FLOAT_MAT4x3",
    "DOUBLE_MAT2",
    "DOUBLE_MAT3",
    "DOUBLE_MAT4",
    "SAMPLER_1D",
    "SAMPLER_2D",
    "SAMPLER_3D",
    "SAMPLER_CUBE",
    "SAMPLER_1D_SHADOW",
    "SAMPLER_2D_SHADOW",
    "UNIFORM",
    "UNIFORM_BLOCK",
    "PROGRAM_INPUT",
    "PROGRAM_OUTPUT",
    "BUFFER_VARIABLE",
    "SHADER_STORAGE_BLOCK",
    "VERTEX_SUBROUTINE",
    "TESS_CONTROL_SUBROUTINE",
    "TESS_EVALUATION_SUBROUTINE",
    "GEOMETRY_SUBROUTINE",
    "FRAGMENT_SUBROUTINE",
    "COMPUTE_SUBROUTINE",
    "VERTEX_SUBROUTINE_UNIFORM",
    "TESS_CONTROL_SUBROUTINE_UNIFORM",
    "TESS_EVALUATION_SUBROUTINE_UNIFORM",
    "GEOMETRY_SUBROUTINE_UNIFORM",
    "FRAGMENT_SUBROUTINE_UNIFORM",
    "COMPUTE_SUBROUTINE_UNIFORM",
    "TRANSFORM_FEEDBACK_VARYING",
    "ACTIVE_RESOURCES",
    "MAX_NAME_LENGTH",
    "MAX_NUM_ACTIVE_VARIABLES",
    "NAME_LENGTH",
    "TYPE",
    "ARRAY_SIZE",
    "OFFSET",
    "BLOCK_INDEX",
    "ARRAY_STRIDE",
    "MATRIX_STRIDE",
    "IS_ROW_MAJOR",
    "ATOMIC_COUNTER_BUFFER_INDEX",
    "BUFFER_BINDING",
    "BUFFER_DATA_SIZE",
    "NUM_ACTIVE_VARIABLES",
    "ACTIVE_VARIABLES",
    "REFERENCED_BY_VERTEX_SHADER",
    "REFERENCED_BY_TESS_CONTROL_SHADER",
    "REFERENCED_BY_TESS_EVALUATION_SHADER",
    "REFERENCED_BY_GEOMETRY_SHADER",
    "REFERENCED_BY_FRAGMENT_SHADER",
    "REFERENCED_BY_COMPUTE_SHADER",
    "TOP_LEVEL_ARRAY_SIZE",
    "TOP_LEVEL_ARRAY_STRIDE",
    "LOCATION",
    "LOCATION_INDEX",
    "IS_PER_PATCH",
    "VERTEX_ATTRIB_ARRAY_ENABLED",
    "VERTEX_ATTRIB_ARRAY_SIZE",
    "VERTEX_ATTRIB_ARRAY_STRIDE",
    "VERTEX_ATTRIB_ARRAY_TYPE",
    "VERTEX_ATTRIB_ARRAY_NORMALIZED",
    "VERTEX_ATTRIB_ARRAY_POINTER",
    "VERTEX_ATTRIB_ARRAY_BUFFER_BINDING",
    "VERTEX_ATTRIB_ARRAY_INTEGER",
    "VERTEX_ATTRIB_ARRAY_DIVISOR",
    "VERTEX_ATTRIB_ARRAY_LONG",
    "VERTEX_ATTRIB_BINDING",
    "VERTEX_ATTRIB_RELATIVE_OFFSET",
    "VERTEX_BINDING_DIVISOR",
    "VERTEX_BINDING_OFFSET",
    "VERTEX_BINDING_STRIDE",
    "VERTEX_BINDING_BUFFER",
    "READ_ONLY",
    "WRITE_ONLY",
    "READ_WRITE",
    "VERTEX_ATTRIB_ARRAY_BARRIER_BIT",
    "ELEMENT_ARRAY_BARRIER_BIT",
    "UNIFORM_BARRIER_BIT",
    "TEXTURE_FETCH_BARRIER_BIT",
    "SHADER_IMAGE_ACCESS_BARRIER_BIT",
    "COMMAND_BARRIER_BIT",
    "PIXEL_BUFFER_BARRIER_BIT",
    "TEXTURE_UPDATE_BARRIER_BIT",
    "BUFFER_UPDATE_BARRIER_BIT",
    "FRAMEBUFFER_BARRIER_BIT",
    "TRANSFORM_FEEDBACK_BARRIER_BIT",
    "ATOMIC_COUNTER_BARRIER_BIT",
    "SHADER_STORAGE_BARRIER_BIT",
    "CLIENT_MAPPED_BUFFER_BARRIER_BIT",
    "QUERY_BUFFER_BARRIER_BIT",
    "ALL_BARRIER_BITS",
    "ALREADY_SIGNALED",
    "TIMEOUT_EXPIRED",
    "CONDITION_SATISFIED",
    "WAIT_FAILED",
    "SYNC_FLUSH_COMMANDS_BIT",
    "SYNC_GPU_COMMANDS_COMPLETE",
    "SYNC_STATUS",
    "SYNC_CONDITION",
    "SYNC_FLAGS",
    "SYNC_FENCE",
    "OBJECT_TYPE",
    "SAMPLES_PASSED",
    "ANY_SAMPLES_PASSED",
    "ANY_SAMPLES_PASSED_CONSERVATIVE",
    "PRIMITIVES_GENERATED",
    "TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN",
    "TIME_ELAPSED",
    "TIMESTAMP",
    "QUERY_RESULT",
    "QUERY_RESULT_AVAILABLE",
    "QUERY_RESULT_NO_WAIT",
    "INTERLEAVED_ATTRIBS",
    "SEPARATE_ATTRIBS",
    "TRANSFORM_FEEDBACK",
    "PATCH_VERTICES",
    "PATCH_DEFAULT_INNER_LEVEL",
    "PATCH_DEFAULT_OUTER_LEVEL",
    "TESS_GEN_MODE",
    "TESS_GEN_SPACING",
    "TESS_GEN_VERTEX_ORDER",
    "TESS_GEN_POINT_MODE",
    "FIRST_VERTEX_CONVENTION",
    "LAST_VERTEX_CONVENTION",
    "PROVOKING_VERTEX",
    "CLEAR",
    "AND",
    "AND_REVERSE",
    "COPY",
    "AND_INVERTED",
    "NOOP",
    "XOR",
    "OR",
    "NOR",
    "EQUIV",
    "LOGIC_INVERT",
    "OR_REVERSE",
    "COPY_INVERTED",
    "OR_INVERTED",
    "NAND",
    "SET",
    "ATOMIC_COUNTER_BUFFER_BINDING",
    "ATOMIC_COUNTER_BUFFER_DATA_SIZE",
    "ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS",
    "UNSIGNED_INT_ATOMIC_COUNTER",
    "DEBUG_SOURCE_API",
    "DEBUG_SOURCE_WINDOW_SYSTEM",
    "DEBUG_SOURCE_SHADER_COMPILER",
    "DEBUG_SOURCE_THIRD_PARTY",
    "DEBUG_SOURCE_APPLICATION",
    "DEBUG_SOURCE_OTHER",
    "DEBUG_TYPE_ERROR",
    "DEBUG_TYPE_DEPRECATED_BEHAVIOR",
    "DEBUG_TYPE_UNDEFINED_BEHAVIOR",
    "DEBUG_TYPE_PORTABILITY",
    "DEBUG_TYPE_PERFORMANCE",
    "DEBUG_TYPE_OTHER",
    "DEBUG_TYPE_MARKER",
    "DEBUG_TYPE_PUSH_GROUP",
    "DEBUG_TYPE_POP_GROUP",
    "DEBUG_SEVERITY_HIGH",
    "DEBUG_SEVERITY_MEDIUM",
    "DEBUG_SEVERITY_LOW",
    "DEBUG_SEVERITY_NOTIFICATION",
    "DEBUG_LOGGED_MESSAGES",
    "DEBUG_NEXT_LOGGED_MESSAGE_LENGTH",
    "DEBUG_GROUP_STACK_DEPTH",
    "BUFFER_OBJECT",
    "SHADER_OBJECT",
    "PROGRAM_OBJECT",
    "VERTEX_ARRAY_OBJECT",
    "QUERY_OBJECT",
    "PROGRAM_PIPELINE_OBJECT",
    "SAMPLER_OBJECT",
    "DRAW_BUFFER0",
    "DRAW_BUFFER1",
    "DRAW_BUFFER2",
    "DRAW_BUFFER3",
    "DRAW_BUFFER4",
    "DRAW_BUFFER5",
    "DRAW_BUFFER6",
    "DRAW_BUFFER7",
    "DRAW_BUFFER8",
    "DRAW_BUFFER9",
    "DRAW_BUFFER10",
    "DRAW_BUFFER11",
    "DRAW_BUFFER12",
    "DRAW_BUFFER13",
    "DRAW_BUFFER14",
    "DRAW_BUFFER15",
    "BACK_LEFT",
    "BACK_RIGHT",
    "FRONT_LEFT",
    "FRONT_RIGHT",
    "LEFT",
    "RIGHT",
    "NONE",
    "UF_1I",
    "UF_2I",
    "UF_3I",
    "UF_4I",
    "UF_1B",
    "UF_2B",
    "UF_3B",
    "UF_4B",
    "UF_1U",
    "UF_2U",
    "UF_3U",
    "UF_4U",
    "UF_1F",
    "UF_2F",
    "UF_3F",
    "UF_4F",
    "UF_MAT2",
    "UF_MAT2x3",
    "UF_MAT2x4",
    "UF_MAT3x2",
    "UF_MAT3",
    "UF_MAT3x4",
    "UF_MAT4x2",
    "UF_MAT4x3",
    "UF_MAT4",
    "UF_MAT2_RM",
    "UF_MAT3_RM",
    "UF_MAT4_RM",
    "IF_INTERNAL_FORMAT",
    "IF_FORMAT",
    "IF_TYPE",
    "IF_BUFFER",
    "IF_COMPONENTS",
    "IF_PIXEL_SIZE",
    "IF_COLOR",
    "IF_FLAGS",
    "IF_CLEAR_TYPE",
]
