#pragma once
#include <stddef.h>
#include <stdint.h>

#define CARAVANGL_CONSTANT [[maybe_unused]] static constexpr

// -----------------------------------------------------------------------------
// Standard GL Types
// -----------------------------------------------------------------------------
typedef uint8_t GLboolean;
typedef uint32_t GLbitfield;
typedef uint32_t GLenum;
typedef uint32_t GLuint;
typedef int32_t GLint;
typedef int32_t GLsizei;
typedef void GLvoid;
typedef char GLchar;
typedef float GLfloat;
typedef float GLclampf;
typedef double GLdouble;
typedef double GLclampd;
typedef int8_t GLbyte;
typedef uint8_t GLubyte;
typedef int16_t GLshort;
typedef uint16_t GLushort;
typedef int64_t GLint64;
typedef uint64_t GLuint64;
typedef intptr_t GLintptr;
typedef ptrdiff_t GLsizeiptr;
typedef uint16_t GLhalf;
typedef uint64_t GLuint64EXT;
typedef int64_t  GLint64EXT;
typedef unsigned short GLbitfield16;

typedef struct __GLsync *GLsync;

// -----------------------------------------------------------------------------
// OpenGL Constants — Strictly per Khronos gl.xml / OpenGL 4.6 Core
// Specification
// -----------------------------------------------------------------------------

// --- Debug ---
CARAVANGL_CONSTANT GLenum GL_DONT_CARE = 0x1100;

// --- Boolean ---
CARAVANGL_CONSTANT GLboolean GL_FALSE = 0;
CARAVANGL_CONSTANT GLboolean GL_TRUE = 1;

// --- Data Types ---
CARAVANGL_CONSTANT GLenum GL_BYTE = 0x1400;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_BYTE = 0x1401;
CARAVANGL_CONSTANT GLenum GL_SHORT = 0x1402;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT = 0x1403;
CARAVANGL_CONSTANT GLenum GL_INT = 0x1404;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT = 0x1405;
CARAVANGL_CONSTANT GLenum GL_FLOAT = 0x1406;
CARAVANGL_CONSTANT GLenum GL_DOUBLE = 0x140A;
CARAVANGL_CONSTANT GLenum GL_HALF_FLOAT = 0x140B;
CARAVANGL_CONSTANT GLenum GL_FIXED = 0x140C;
CARAVANGL_CONSTANT GLenum GL_INT_2_10_10_10_REV = 0x8D9F;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B;

// --- Primitives ---
CARAVANGL_CONSTANT GLenum GL_POINTS = 0x0000;
CARAVANGL_CONSTANT GLenum GL_LINES = 0x0001;
CARAVANGL_CONSTANT GLenum GL_LINE_LOOP = 0x0002;
CARAVANGL_CONSTANT GLenum GL_LINE_STRIP = 0x0003;
CARAVANGL_CONSTANT GLenum GL_TRIANGLES = 0x0004;
CARAVANGL_CONSTANT GLenum GL_TRIANGLE_STRIP = 0x0005;
CARAVANGL_CONSTANT GLenum GL_TRIANGLE_FAN = 0x0006;
CARAVANGL_CONSTANT GLenum GL_LINES_ADJACENCY = 0x000A;
CARAVANGL_CONSTANT GLenum GL_LINE_STRIP_ADJACENCY = 0x000B;
CARAVANGL_CONSTANT GLenum GL_TRIANGLES_ADJACENCY = 0x000C;
CARAVANGL_CONSTANT GLenum GL_TRIANGLE_STRIP_ADJACENCY = 0x000D;
CARAVANGL_CONSTANT GLenum GL_PATCHES = 0x000E;

// --- Blending ---
CARAVANGL_CONSTANT GLenum GL_ZERO = 0;
CARAVANGL_CONSTANT GLenum GL_ONE = 1;
CARAVANGL_CONSTANT GLenum GL_SRC_COLOR = 0x0300;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_SRC_COLOR = 0x0301;
CARAVANGL_CONSTANT GLenum GL_SRC_ALPHA = 0x0302;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_SRC_ALPHA = 0x0303;
CARAVANGL_CONSTANT GLenum GL_DST_ALPHA = 0x0304;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_DST_ALPHA = 0x0305;
CARAVANGL_CONSTANT GLenum GL_DST_COLOR = 0x0306;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_DST_COLOR = 0x0307;
CARAVANGL_CONSTANT GLenum GL_SRC_ALPHA_SATURATE = 0x0308;
CARAVANGL_CONSTANT GLenum GL_CONSTANT_COLOR = 0x8001;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_CONSTANT_COLOR = 0x8002;
CARAVANGL_CONSTANT GLenum GL_CONSTANT_ALPHA = 0x8003;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004;
CARAVANGL_CONSTANT GLenum GL_SRC1_COLOR = 0x88F9;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_SRC1_COLOR = 0x88FA;
CARAVANGL_CONSTANT GLenum GL_SRC1_ALPHA = 0x8589;
CARAVANGL_CONSTANT GLenum GL_ONE_MINUS_SRC1_ALPHA = 0x88FB;

// --- Blend Equations ---
CARAVANGL_CONSTANT GLenum GL_FUNC_ADD = 0x8006;
CARAVANGL_CONSTANT GLenum GL_FUNC_SUBTRACT = 0x800A;
CARAVANGL_CONSTANT GLenum GL_FUNC_REVERSE_SUBTRACT = 0x800B;
CARAVANGL_CONSTANT GLenum GL_MIN = 0x8007;
CARAVANGL_CONSTANT GLenum GL_MAX = 0x8008;

// --- Clear Bits ---
CARAVANGL_CONSTANT GLbitfield GL_DEPTH_BUFFER_BIT = 0x00000100;
CARAVANGL_CONSTANT GLbitfield GL_STENCIL_BUFFER_BIT = 0x00000400;
CARAVANGL_CONSTANT GLbitfield GL_COLOR_BUFFER_BIT = 0x00004000;

// --- Buffer Types (for ClearBuffer) ---
CARAVANGL_CONSTANT GLenum GL_COLOR = 0x1800;
CARAVANGL_CONSTANT GLenum GL_DEPTH = 0x1801;
CARAVANGL_CONSTANT GLenum GL_STENCIL = 0x1802;

// --- Errors ---
CARAVANGL_CONSTANT GLenum GL_NO_ERROR = 0;
CARAVANGL_CONSTANT GLenum GL_INVALID_ENUM = 0x0500;
CARAVANGL_CONSTANT GLenum GL_INVALID_VALUE = 0x0501;
CARAVANGL_CONSTANT GLenum GL_INVALID_OPERATION = 0x0502;
CARAVANGL_CONSTANT GLenum GL_STACK_OVERFLOW = 0x0503;
CARAVANGL_CONSTANT GLenum GL_STACK_UNDERFLOW = 0x0504;
CARAVANGL_CONSTANT GLenum GL_OUT_OF_MEMORY = 0x0505;
CARAVANGL_CONSTANT GLenum GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_LOST = 0x0507;

// --- String Queries ---
CARAVANGL_CONSTANT GLenum GL_VENDOR = 0x1F00;
CARAVANGL_CONSTANT GLenum GL_RENDERER = 0x1F01;
CARAVANGL_CONSTANT GLenum GL_VERSION = 0x1F02;
CARAVANGL_CONSTANT GLenum GL_EXTENSIONS = 0x1F03;
CARAVANGL_CONSTANT GLenum GL_SHADING_LANGUAGE_VERSION = 0x8B8C;

// --- Face / Winding ---
CARAVANGL_CONSTANT GLenum GL_CW = 0x0900;
CARAVANGL_CONSTANT GLenum GL_CCW = 0x0901;
CARAVANGL_CONSTANT GLenum GL_FRONT = 0x0404;
CARAVANGL_CONSTANT GLenum GL_BACK = 0x0405;
CARAVANGL_CONSTANT GLenum GL_FRONT_AND_BACK = 0x0408;

// --- Polygon Mode ---
CARAVANGL_CONSTANT GLenum GL_POINT = 0x1B00;
CARAVANGL_CONSTANT GLenum GL_LINE = 0x1B01;
CARAVANGL_CONSTANT GLenum GL_FILL = 0x1B02;

// --- Depth / Stencil Functions ---
CARAVANGL_CONSTANT GLenum GL_NEVER = 0x0200;
CARAVANGL_CONSTANT GLenum GL_LESS = 0x0201;
CARAVANGL_CONSTANT GLenum GL_EQUAL = 0x0202;
CARAVANGL_CONSTANT GLenum GL_LEQUAL = 0x0203;
CARAVANGL_CONSTANT GLenum GL_GREATER = 0x0204;
CARAVANGL_CONSTANT GLenum GL_NOTEQUAL = 0x0205;
CARAVANGL_CONSTANT GLenum GL_GEQUAL = 0x0206;
CARAVANGL_CONSTANT GLenum GL_ALWAYS = 0x0207;

// --- Stencil Operations ---
CARAVANGL_CONSTANT GLenum GL_KEEP = 0x1E00;
CARAVANGL_CONSTANT GLenum GL_REPLACE = 0x1E01;
CARAVANGL_CONSTANT GLenum GL_INCR = 0x1E02;
CARAVANGL_CONSTANT GLenum GL_DECR = 0x1E03;
CARAVANGL_CONSTANT GLenum GL_INVERT = 0x150A;
CARAVANGL_CONSTANT GLenum GL_INCR_WRAP = 0x8507;
CARAVANGL_CONSTANT GLenum GL_DECR_WRAP = 0x8508;

// --- Enable Caps ---
CARAVANGL_CONSTANT GLenum GL_CULL_FACE = 0x0B44;
CARAVANGL_CONSTANT GLenum GL_DEPTH_TEST = 0x0B71;
CARAVANGL_CONSTANT GLenum GL_STENCIL_TEST = 0x0B90;
CARAVANGL_CONSTANT GLenum GL_BLEND = 0x0BE2;
CARAVANGL_CONSTANT GLenum GL_SCISSOR_TEST = 0x0C11;
CARAVANGL_CONSTANT GLenum GL_COLOR_LOGIC_OP = 0x0BF2;
CARAVANGL_CONSTANT GLenum GL_DITHER = 0x0BD0;
CARAVANGL_CONSTANT GLenum GL_LINE_SMOOTH = 0x0B20;
CARAVANGL_CONSTANT GLenum GL_POLYGON_SMOOTH = 0x0B41;
CARAVANGL_CONSTANT GLenum GL_POLYGON_OFFSET_POINT = 0x2A01;
CARAVANGL_CONSTANT GLenum GL_POLYGON_OFFSET_LINE = 0x2A02;
CARAVANGL_CONSTANT GLenum GL_POLYGON_OFFSET_FILL = 0x8037;
CARAVANGL_CONSTANT GLenum GL_MULTISAMPLE = 0x809D;
CARAVANGL_CONSTANT GLenum GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
CARAVANGL_CONSTANT GLenum GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
CARAVANGL_CONSTANT GLenum GL_SAMPLE_COVERAGE = 0x80A0;
CARAVANGL_CONSTANT GLenum GL_SAMPLE_SHADING = 0x8C36;
CARAVANGL_CONSTANT GLenum GL_SAMPLE_MASK = 0x8E51;
CARAVANGL_CONSTANT GLenum GL_PRIMITIVE_RESTART = 0x8F9D;
CARAVANGL_CONSTANT GLenum GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69;
CARAVANGL_CONSTANT GLenum GL_RASTERIZER_DISCARD = 0x8C89;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_SRGB = 0x8DB9;
CARAVANGL_CONSTANT GLenum GL_DEPTH_CLAMP = 0x864F;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_SEAMLESS = 0x884F;
CARAVANGL_CONSTANT GLenum GL_PROGRAM_POINT_SIZE = 0x8642;
CARAVANGL_CONSTANT GLenum GL_DEBUG_OUTPUT = 0x92E0;
CARAVANGL_CONSTANT GLenum GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242;

// --- GetIntegerv / State Queries ---
CARAVANGL_CONSTANT GLenum GL_VIEWPORT = 0x0BA2;
CARAVANGL_CONSTANT GLenum GL_DEPTH_RANGE = 0x0B70;
CARAVANGL_CONSTANT GLenum GL_DEPTH_WRITEMASK = 0x0B72;
CARAVANGL_CONSTANT GLenum GL_DEPTH_CLEAR_VALUE = 0x0B73;
CARAVANGL_CONSTANT GLenum GL_DEPTH_FUNC = 0x0B74;
CARAVANGL_CONSTANT GLenum GL_STENCIL_CLEAR_VALUE = 0x0B91;
CARAVANGL_CONSTANT GLenum GL_STENCIL_FUNC = 0x0B92;
CARAVANGL_CONSTANT GLenum GL_STENCIL_VALUE_MASK = 0x0B93;
CARAVANGL_CONSTANT GLenum GL_STENCIL_FAIL = 0x0B94;
CARAVANGL_CONSTANT GLenum GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95;
CARAVANGL_CONSTANT GLenum GL_STENCIL_PASS_DEPTH_PASS = 0x0B96;
CARAVANGL_CONSTANT GLenum GL_STENCIL_REF = 0x0B97;
CARAVANGL_CONSTANT GLenum GL_STENCIL_WRITEMASK = 0x0B98;
CARAVANGL_CONSTANT GLenum GL_SCISSOR_BOX = 0x0C10;
CARAVANGL_CONSTANT GLenum GL_COLOR_CLEAR_VALUE = 0x0C22;
CARAVANGL_CONSTANT GLenum GL_COLOR_WRITEMASK = 0x0C23;
CARAVANGL_CONSTANT GLenum GL_UNPACK_SWAP_BYTES = 0x0CF0;
CARAVANGL_CONSTANT GLenum GL_UNPACK_LSB_FIRST = 0x0CF1;
CARAVANGL_CONSTANT GLenum GL_UNPACK_ROW_LENGTH = 0x0CF2;
CARAVANGL_CONSTANT GLenum GL_UNPACK_SKIP_ROWS = 0x0CF3;
CARAVANGL_CONSTANT GLenum GL_UNPACK_SKIP_PIXELS = 0x0CF4;
CARAVANGL_CONSTANT GLenum GL_UNPACK_ALIGNMENT = 0x0CF5;
CARAVANGL_CONSTANT GLenum GL_PACK_SWAP_BYTES = 0x0D00;
CARAVANGL_CONSTANT GLenum GL_PACK_LSB_FIRST = 0x0D01;
CARAVANGL_CONSTANT GLenum GL_PACK_ROW_LENGTH = 0x0D02;
CARAVANGL_CONSTANT GLenum GL_PACK_SKIP_ROWS = 0x0D03;
CARAVANGL_CONSTANT GLenum GL_PACK_SKIP_PIXELS = 0x0D04;
CARAVANGL_CONSTANT GLenum GL_PACK_ALIGNMENT = 0x0D05;
CARAVANGL_CONSTANT GLenum GL_MAX_TEXTURE_SIZE = 0x0D33;
CARAVANGL_CONSTANT GLenum GL_MAX_VIEWPORT_DIMS = 0x0D3A;
CARAVANGL_CONSTANT GLenum GL_SUBPIXEL_BITS = 0x0D50;
CARAVANGL_CONSTANT GLenum GL_MAX_ELEMENTS_VERTICES = 0x80E8;
CARAVANGL_CONSTANT GLenum GL_MAX_ELEMENTS_INDICES = 0x80E9;
CARAVANGL_CONSTANT GLenum GL_MAX_3D_TEXTURE_SIZE = 0x8073;
CARAVANGL_CONSTANT GLenum GL_MAX_DRAW_BUFFERS = 0x8824;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_ATTRIBS = 0x8869;
CARAVANGL_CONSTANT GLenum GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
CARAVANGL_CONSTANT GLenum GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
CARAVANGL_CONSTANT GLenum GL_MAX_VARYING_FLOATS = 0x8B4B;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
CARAVANGL_CONSTANT GLenum GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
CARAVANGL_CONSTANT GLenum GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
CARAVANGL_CONSTANT GLenum GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
CARAVANGL_CONSTANT GLenum GL_MAX_SAMPLES = 0x8D57;
CARAVANGL_CONSTANT GLenum GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8;
CARAVANGL_CONSTANT GLenum GL_MAX_TEXTURE_LOD_BIAS = 0x84FD;
CARAVANGL_CONSTANT GLenum GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C;
CARAVANGL_CONSTANT GLenum GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF;
CARAVANGL_CONSTANT GLenum GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B;
CARAVANGL_CONSTANT GLenum GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F;
CARAVANGL_CONSTANT GLenum GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30;
CARAVANGL_CONSTANT GLenum GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B;
CARAVANGL_CONSTANT GLenum GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C;
CARAVANGL_CONSTANT GLenum GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D;
CARAVANGL_CONSTANT GLenum GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD;
CARAVANGL_CONSTANT GLenum GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF;
CARAVANGL_CONSTANT GLenum GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x90EB;
CARAVANGL_CONSTANT GLenum GL_MAX_IMAGE_UNITS = 0x8F38;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_IMAGE_UNIFORMS = 0x90CA;
CARAVANGL_CONSTANT GLenum GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 0x90CE;
CARAVANGL_CONSTANT GLenum GL_MAX_COMBINED_IMAGE_UNIFORMS = 0x90CF;
CARAVANGL_CONSTANT GLenum GL_MAX_GEOMETRY_IMAGE_UNIFORMS = 0x90CD;
CARAVANGL_CONSTANT GLenum GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS = 0x90CB;
CARAVANGL_CONSTANT GLenum GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS = 0x90CC;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6;
CARAVANGL_CONSTANT GLenum GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA;
CARAVANGL_CONSTANT GLenum GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7;
CARAVANGL_CONSTANT GLenum GL_NUM_EXTENSIONS = 0x821D;
CARAVANGL_CONSTANT GLenum GL_MAJOR_VERSION = 0x821B;
CARAVANGL_CONSTANT GLenum GL_MINOR_VERSION = 0x821C;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_FLAGS = 0x821E;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_PROFILE_MASK = 0x9126;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x00000001;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT = 0x00000004;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_CORE_PROFILE_BIT = 0x00000001;
CARAVANGL_CONSTANT GLenum GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 0x00000002;

// --- Texture Targets ---
CARAVANGL_CONSTANT GLenum GL_TEXTURE_1D = 0x0DE0;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_2D = 0x0DE1;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_3D = 0x806F;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_1D_ARRAY = 0x8C18;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_2D_ARRAY = 0x8C1A;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_RECTANGLE = 0x84F5;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP = 0x8513;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_2D_MULTISAMPLE = 0x9100;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_BUFFER = 0x8C2A;
CARAVANGL_CONSTANT GLenum GL_PROXY_TEXTURE_1D = 0x8063;
CARAVANGL_CONSTANT GLenum GL_PROXY_TEXTURE_2D = 0x8064;
CARAVANGL_CONSTANT GLenum GL_PROXY_TEXTURE_3D = 0x8070;
CARAVANGL_CONSTANT GLenum GL_PROXY_TEXTURE_CUBE_MAP = 0x851B;

// --- Cube Map Faces ---
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A;

// --- Texture Parameters ---
CARAVANGL_CONSTANT GLenum GL_TEXTURE_MIN_FILTER = 0x2801;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_MAG_FILTER = 0x2800;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_WRAP_S = 0x2802;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_WRAP_T = 0x2803;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_WRAP_R = 0x8072;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_BASE_LEVEL = 0x813C;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_MAX_LEVEL = 0x813D;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_MIN_LOD = 0x813A;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_MAX_LOD = 0x813B;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_LOD_BIAS = 0x8501;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_COMPARE_MODE = 0x884C;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_COMPARE_FUNC = 0x884D;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_SWIZZLE_R = 0x8E42;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_SWIZZLE_G = 0x8E43;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_SWIZZLE_B = 0x8E44;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_SWIZZLE_A = 0x8E45;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_SWIZZLE_RGBA = 0x8E46;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_BORDER_COLOR = 0x1004;
CARAVANGL_CONSTANT GLenum GL_TEXTURE_MAX_ANISOTROPY =
    0x84FE; // ARB_texture_filter_anisotropic (core 4.6)
CARAVANGL_CONSTANT GLenum GL_DEPTH_STENCIL_TEXTURE_MODE = 0x90EA;

// --- Texture Filters ---
CARAVANGL_CONSTANT GLenum GL_NEAREST = 0x2600;
CARAVANGL_CONSTANT GLenum GL_LINEAR = 0x2601;
CARAVANGL_CONSTANT GLenum GL_NEAREST_MIPMAP_NEAREST = 0x2700;
CARAVANGL_CONSTANT GLenum GL_LINEAR_MIPMAP_NEAREST = 0x2701;
CARAVANGL_CONSTANT GLenum GL_NEAREST_MIPMAP_LINEAR = 0x2702;
CARAVANGL_CONSTANT GLenum GL_LINEAR_MIPMAP_LINEAR = 0x2703;

// --- Texture Wrap Modes ---
CARAVANGL_CONSTANT GLenum GL_REPEAT = 0x2901;
CARAVANGL_CONSTANT GLenum GL_CLAMP_TO_EDGE = 0x812F;
CARAVANGL_CONSTANT GLenum GL_CLAMP_TO_BORDER = 0x812D;
CARAVANGL_CONSTANT GLenum GL_MIRRORED_REPEAT = 0x8370;
CARAVANGL_CONSTANT GLenum GL_MIRROR_CLAMP_TO_EDGE = 0x8743;

// --- Texture Compare Modes ---
CARAVANGL_CONSTANT GLenum GL_COMPARE_REF_TO_TEXTURE = 0x884E;
CARAVANGL_CONSTANT GLenum GL_NONE = 0;

// --- Texture Units ---
CARAVANGL_CONSTANT GLenum GL_TEXTURE0 = 0x84C0;
CARAVANGL_CONSTANT GLenum GL_TEXTURE1 = 0x84C1;
CARAVANGL_CONSTANT GLenum GL_TEXTURE2 = 0x84C2;
CARAVANGL_CONSTANT GLenum GL_TEXTURE3 = 0x84C3;
CARAVANGL_CONSTANT GLenum GL_TEXTURE4 = 0x84C4;
CARAVANGL_CONSTANT GLenum GL_TEXTURE5 = 0x84C5;
CARAVANGL_CONSTANT GLenum GL_TEXTURE6 = 0x84C6;
CARAVANGL_CONSTANT GLenum GL_TEXTURE7 = 0x84C7;
CARAVANGL_CONSTANT GLenum GL_TEXTURE8 = 0x84C8;
CARAVANGL_CONSTANT GLenum GL_TEXTURE9 = 0x84C9;
CARAVANGL_CONSTANT GLenum GL_TEXTURE10 = 0x84CA;
CARAVANGL_CONSTANT GLenum GL_TEXTURE11 = 0x84CB;
CARAVANGL_CONSTANT GLenum GL_TEXTURE12 = 0x84CC;
CARAVANGL_CONSTANT GLenum GL_TEXTURE13 = 0x84CD;
CARAVANGL_CONSTANT GLenum GL_TEXTURE14 = 0x84CE;
CARAVANGL_CONSTANT GLenum GL_TEXTURE15 = 0x84CF;
CARAVANGL_CONSTANT GLenum GL_TEXTURE16 = 0x84D0;
CARAVANGL_CONSTANT GLenum GL_TEXTURE17 = 0x84D1;
CARAVANGL_CONSTANT GLenum GL_TEXTURE18 = 0x84D2;
CARAVANGL_CONSTANT GLenum GL_TEXTURE19 = 0x84D3;
CARAVANGL_CONSTANT GLenum GL_TEXTURE20 = 0x84D4;
CARAVANGL_CONSTANT GLenum GL_TEXTURE21 = 0x84D5;
CARAVANGL_CONSTANT GLenum GL_TEXTURE22 = 0x84D6;
CARAVANGL_CONSTANT GLenum GL_TEXTURE23 = 0x84D7;
CARAVANGL_CONSTANT GLenum GL_TEXTURE24 = 0x84D8;
CARAVANGL_CONSTANT GLenum GL_TEXTURE25 = 0x84D9;
CARAVANGL_CONSTANT GLenum GL_TEXTURE26 = 0x84DA;
CARAVANGL_CONSTANT GLenum GL_TEXTURE27 = 0x84DB;
CARAVANGL_CONSTANT GLenum GL_TEXTURE28 = 0x84DC;
CARAVANGL_CONSTANT GLenum GL_TEXTURE29 = 0x84DD;
CARAVANGL_CONSTANT GLenum GL_TEXTURE30 = 0x84DE;
CARAVANGL_CONSTANT GLenum GL_TEXTURE31 = 0x84DF;

// --- Sized Internal Formats (Color) ---
CARAVANGL_CONSTANT GLenum GL_R8 = 0x8229;
CARAVANGL_CONSTANT GLenum GL_R8_SNORM = 0x8F94;
CARAVANGL_CONSTANT GLenum GL_R16 = 0x822A;
CARAVANGL_CONSTANT GLenum GL_R16_SNORM = 0x8F98;
CARAVANGL_CONSTANT GLenum GL_RG8 = 0x822B;
CARAVANGL_CONSTANT GLenum GL_RG8_SNORM = 0x8F95;
CARAVANGL_CONSTANT GLenum GL_RG16 = 0x822C;
CARAVANGL_CONSTANT GLenum GL_RG16_SNORM = 0x8F99;
CARAVANGL_CONSTANT GLenum GL_R3_G3_B2 = 0x2A10;
CARAVANGL_CONSTANT GLenum GL_RGB4 = 0x804F;
CARAVANGL_CONSTANT GLenum GL_RGB5 = 0x8050;
CARAVANGL_CONSTANT GLenum GL_RGB8 = 0x8051;
CARAVANGL_CONSTANT GLenum GL_RGB8_SNORM = 0x8F96;
CARAVANGL_CONSTANT GLenum GL_RGB10 = 0x8052;
CARAVANGL_CONSTANT GLenum GL_RGB12 = 0x8053;
CARAVANGL_CONSTANT GLenum GL_RGB16 = 0x8054;
CARAVANGL_CONSTANT GLenum GL_RGB16_SNORM = 0x8F9A;
CARAVANGL_CONSTANT GLenum GL_RGBA2 = 0x8055;
CARAVANGL_CONSTANT GLenum GL_RGBA4 = 0x8056;
CARAVANGL_CONSTANT GLenum GL_RGB5_A1 = 0x8057;
CARAVANGL_CONSTANT GLenum GL_RGBA8 = 0x8058;
CARAVANGL_CONSTANT GLenum GL_RGBA8_SNORM = 0x8F97;
CARAVANGL_CONSTANT GLenum GL_RGB10_A2 = 0x8059;
CARAVANGL_CONSTANT GLenum GL_RGB10_A2UI = 0x906F;
CARAVANGL_CONSTANT GLenum GL_RGBA12 = 0x805A;
CARAVANGL_CONSTANT GLenum GL_RGBA16 = 0x805B;
CARAVANGL_CONSTANT GLenum GL_RGBA16_SNORM = 0x8F9B;
CARAVANGL_CONSTANT GLenum GL_SRGB8 = 0x8C41;
CARAVANGL_CONSTANT GLenum GL_SRGB8_ALPHA8 = 0x8C43;
CARAVANGL_CONSTANT GLenum GL_R16F = 0x822D;
CARAVANGL_CONSTANT GLenum GL_RG16F = 0x822F;
CARAVANGL_CONSTANT GLenum GL_RGB16F = 0x881B;
CARAVANGL_CONSTANT GLenum GL_RGBA16F = 0x881A;
CARAVANGL_CONSTANT GLenum GL_R32F = 0x822E;
CARAVANGL_CONSTANT GLenum GL_RG32F = 0x8230;
CARAVANGL_CONSTANT GLenum GL_RGB32F = 0x8815;
CARAVANGL_CONSTANT GLenum GL_RGBA32F = 0x8814;
CARAVANGL_CONSTANT GLenum GL_R11F_G11F_B10F = 0x8C3A;
CARAVANGL_CONSTANT GLenum GL_RGB9_E5 = 0x8C3D;
CARAVANGL_CONSTANT GLenum GL_R8I = 0x8231;
CARAVANGL_CONSTANT GLenum GL_R8UI = 0x8232;
CARAVANGL_CONSTANT GLenum GL_R16I = 0x8233;
CARAVANGL_CONSTANT GLenum GL_R16UI = 0x8234;
CARAVANGL_CONSTANT GLenum GL_R32I = 0x8235;
CARAVANGL_CONSTANT GLenum GL_R32UI = 0x8236;
CARAVANGL_CONSTANT GLenum GL_RG8I = 0x8237;
CARAVANGL_CONSTANT GLenum GL_RG8UI = 0x8238;
CARAVANGL_CONSTANT GLenum GL_RG16I = 0x8239;
CARAVANGL_CONSTANT GLenum GL_RG16UI = 0x823A;
CARAVANGL_CONSTANT GLenum GL_RG32I = 0x823B;
CARAVANGL_CONSTANT GLenum GL_RG32UI = 0x823C;
CARAVANGL_CONSTANT GLenum GL_RGB8I = 0x8D8F;
CARAVANGL_CONSTANT GLenum GL_RGB8UI = 0x8D7D;
CARAVANGL_CONSTANT GLenum GL_RGB16I = 0x8D89;
CARAVANGL_CONSTANT GLenum GL_RGB16UI = 0x8D77;
CARAVANGL_CONSTANT GLenum GL_RGB32I = 0x8D83;
CARAVANGL_CONSTANT GLenum GL_RGB32UI = 0x8D71;
CARAVANGL_CONSTANT GLenum GL_RGBA8I = 0x8D8E;
CARAVANGL_CONSTANT GLenum GL_RGBA8UI = 0x8D7C;
CARAVANGL_CONSTANT GLenum GL_RGBA16I = 0x8D88;
CARAVANGL_CONSTANT GLenum GL_RGBA16UI = 0x8D76;
CARAVANGL_CONSTANT GLenum GL_RGBA32I = 0x8D82;
CARAVANGL_CONSTANT GLenum GL_RGBA32UI = 0x8D70;

// --- Sized Internal Formats (Depth / Stencil) ---
CARAVANGL_CONSTANT GLenum GL_DEPTH_COMPONENT16 = 0x81A5;
CARAVANGL_CONSTANT GLenum GL_DEPTH_COMPONENT24 = 0x81A6;
CARAVANGL_CONSTANT GLenum GL_DEPTH_COMPONENT32 = 0x81A7;
CARAVANGL_CONSTANT GLenum GL_DEPTH_COMPONENT32F = 0x8CAC;
CARAVANGL_CONSTANT GLenum GL_DEPTH24_STENCIL8 = 0x88F0;
CARAVANGL_CONSTANT GLenum GL_DEPTH32F_STENCIL8 = 0x8CAD;
CARAVANGL_CONSTANT GLenum GL_STENCIL_INDEX1 = 0x8D46;
CARAVANGL_CONSTANT GLenum GL_STENCIL_INDEX4 = 0x8D47;
CARAVANGL_CONSTANT GLenum GL_STENCIL_INDEX8 = 0x8D48;
CARAVANGL_CONSTANT GLenum GL_STENCIL_INDEX16 = 0x8D49;

// --- Compressed Internal Formats ---
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RED = 0x8225;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RG = 0x8226;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RGB = 0x84ED;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RGBA = 0x84EE;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_SRGB = 0x8C48;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_SRGB_ALPHA = 0x8C49;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RED_RGTC1 = 0x8DBB;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RG_RGTC2 = 0x8DBD;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RGBA_BPTC_UNORM = 0x8E8C;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM = 0x8E8D;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT = 0x8E8E;
CARAVANGL_CONSTANT GLenum GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT = 0x8E8F;

// --- Base / Unsized Formats ---
CARAVANGL_CONSTANT GLenum GL_RED = 0x1903;
CARAVANGL_CONSTANT GLenum GL_RG = 0x8227;
CARAVANGL_CONSTANT GLenum GL_RGB = 0x1907;
CARAVANGL_CONSTANT GLenum GL_RGBA = 0x1908;
CARAVANGL_CONSTANT GLenum GL_BGR = 0x80E0;
CARAVANGL_CONSTANT GLenum GL_BGRA = 0x80E1;
CARAVANGL_CONSTANT GLenum GL_RED_INTEGER = 0x8D94;
CARAVANGL_CONSTANT GLenum GL_RG_INTEGER = 0x8228;
CARAVANGL_CONSTANT GLenum GL_RGB_INTEGER = 0x8D98;
CARAVANGL_CONSTANT GLenum GL_RGBA_INTEGER = 0x8D99;
CARAVANGL_CONSTANT GLenum GL_BGR_INTEGER = 0x8D9A;
CARAVANGL_CONSTANT GLenum GL_BGRA_INTEGER = 0x8D9B;
CARAVANGL_CONSTANT GLenum GL_STENCIL_INDEX = 0x1901;
CARAVANGL_CONSTANT GLenum GL_DEPTH_COMPONENT = 0x1902;
CARAVANGL_CONSTANT GLenum GL_DEPTH_STENCIL = 0x84F9;

// --- Texture Swizzle Values ---
CARAVANGL_CONSTANT GLenum GL_RED_COMPONENT =
    0x1903; // alias to GL_RED in swizzle context
CARAVANGL_CONSTANT GLenum GL_GREEN = 0x1904;
CARAVANGL_CONSTANT GLenum GL_BLUE = 0x1905;
CARAVANGL_CONSTANT GLenum GL_ALPHA = 0x1906;

// --- Buffer Targets ---
CARAVANGL_CONSTANT GLenum GL_ARRAY_BUFFER = 0x8892;
CARAVANGL_CONSTANT GLenum GL_ELEMENT_ARRAY_BUFFER = 0x8893;
CARAVANGL_CONSTANT GLenum GL_PIXEL_PACK_BUFFER = 0x88EB;
CARAVANGL_CONSTANT GLenum GL_PIXEL_UNPACK_BUFFER = 0x88EC;
CARAVANGL_CONSTANT GLenum GL_UNIFORM_BUFFER = 0x8A11;
CARAVANGL_CONSTANT GLenum GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E;
CARAVANGL_CONSTANT GLenum GL_COPY_READ_BUFFER = 0x8F36;
CARAVANGL_CONSTANT GLenum GL_COPY_WRITE_BUFFER = 0x8F37;
CARAVANGL_CONSTANT GLenum GL_DRAW_INDIRECT_BUFFER = 0x8F3F;
CARAVANGL_CONSTANT GLenum GL_SHADER_STORAGE_BUFFER = 0x90D2;
CARAVANGL_CONSTANT GLenum GL_DISPATCH_INDIRECT_BUFFER = 0x90EE;
CARAVANGL_CONSTANT GLenum GL_QUERY_BUFFER = 0x9192;

// --- Buffer Usage ---
CARAVANGL_CONSTANT GLenum GL_STREAM_DRAW = 0x88E0;
CARAVANGL_CONSTANT GLenum GL_STREAM_READ = 0x88E1;
CARAVANGL_CONSTANT GLenum GL_STREAM_COPY = 0x88E2;
CARAVANGL_CONSTANT GLenum GL_STATIC_DRAW = 0x88E4;
CARAVANGL_CONSTANT GLenum GL_STATIC_READ = 0x88E5;
CARAVANGL_CONSTANT GLenum GL_STATIC_COPY = 0x88E6;
CARAVANGL_CONSTANT GLenum GL_DYNAMIC_DRAW = 0x88E8;
CARAVANGL_CONSTANT GLenum GL_DYNAMIC_READ = 0x88E9;
CARAVANGL_CONSTANT GLenum GL_DYNAMIC_COPY = 0x88EA;

// --- Buffer Storage / Map Bits ---
CARAVANGL_CONSTANT GLbitfield GL_MAP_READ_BIT = 0x0001;
CARAVANGL_CONSTANT GLbitfield GL_MAP_WRITE_BIT = 0x0002;
CARAVANGL_CONSTANT GLbitfield GL_MAP_INVALIDATE_RANGE_BIT = 0x0004;
CARAVANGL_CONSTANT GLbitfield GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008;
CARAVANGL_CONSTANT GLbitfield GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010;
CARAVANGL_CONSTANT GLbitfield GL_MAP_UNSYNCHRONIZED_BIT = 0x0020;
CARAVANGL_CONSTANT GLbitfield GL_MAP_PERSISTENT_BIT = 0x0040;
CARAVANGL_CONSTANT GLbitfield GL_MAP_COHERENT_BIT = 0x0080;
CARAVANGL_CONSTANT GLbitfield GL_DYNAMIC_STORAGE_BIT = 0x0100;
CARAVANGL_CONSTANT GLbitfield GL_CLIENT_STORAGE_BIT = 0x0200;

// --- Convenience Composite Flags (non-spec, CaravanGL helpers) ---
CARAVANGL_CONSTANT GLbitfield GL_PERSISTENT_WRITE_FLAGS =
    (GL_MAP_WRITE_BIT | GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT);

// --- Buffer Parameter Names ---
CARAVANGL_CONSTANT GLenum GL_BUFFER_SIZE = 0x8764;
CARAVANGL_CONSTANT GLenum GL_BUFFER_USAGE = 0x8765;
CARAVANGL_CONSTANT GLenum GL_BUFFER_ACCESS = 0x88BB;
CARAVANGL_CONSTANT GLenum GL_BUFFER_MAPPED = 0x88BC;
CARAVANGL_CONSTANT GLenum GL_BUFFER_MAP_POINTER = 0x88BD;
CARAVANGL_CONSTANT GLenum GL_BUFFER_ACCESS_FLAGS = 0x911F;
CARAVANGL_CONSTANT GLenum GL_BUFFER_MAP_LENGTH = 0x9120;
CARAVANGL_CONSTANT GLenum GL_BUFFER_MAP_OFFSET = 0x9121;
CARAVANGL_CONSTANT GLenum GL_BUFFER_IMMUTABLE_STORAGE = 0x821F;
CARAVANGL_CONSTANT GLenum GL_BUFFER_STORAGE_FLAGS = 0x8220;

// --- Framebuffer ---
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER = 0x8D40;
CARAVANGL_CONSTANT GLenum GL_READ_FRAMEBUFFER = 0x8CA8;
CARAVANGL_CONSTANT GLenum GL_DRAW_FRAMEBUFFER = 0x8CA9;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER = 0x8D41;

CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT0 = 0x8CE0;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT1 = 0x8CE1;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT2 = 0x8CE2;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT3 = 0x8CE3;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT4 = 0x8CE4;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT5 = 0x8CE5;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT6 = 0x8CE6;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT7 = 0x8CE7;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT8 = 0x8CE8;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT9 = 0x8CE9;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT10 = 0x8CEA;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT11 = 0x8CEB;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT12 = 0x8CEC;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT13 = 0x8CED;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT14 = 0x8CEE;
CARAVANGL_CONSTANT GLenum GL_COLOR_ATTACHMENT15 = 0x8CEF;
CARAVANGL_CONSTANT GLenum GL_DEPTH_ATTACHMENT = 0x8D00;
CARAVANGL_CONSTANT GLenum GL_STENCIL_ATTACHMENT = 0x8D20;
CARAVANGL_CONSTANT GLenum GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;

CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_DEFAULT = 0x8218;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_UNDEFINED = 0x8219;

CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE =
    0x8CD3;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
CARAVANGL_CONSTANT GLenum GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;

// --- Renderbuffer ---
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_WIDTH = 0x8D42;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_HEIGHT = 0x8D43;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_RED_SIZE = 0x8D50;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
CARAVANGL_CONSTANT GLenum GL_RENDERBUFFER_SAMPLES = 0x8CAB;

// --- Shaders ---
CARAVANGL_CONSTANT GLenum GL_FRAGMENT_SHADER = 0x8B30;
CARAVANGL_CONSTANT GLenum GL_VERTEX_SHADER = 0x8B31;
CARAVANGL_CONSTANT GLenum GL_GEOMETRY_SHADER = 0x8DD9;
CARAVANGL_CONSTANT GLenum GL_TESS_EVALUATION_SHADER = 0x8E87;
CARAVANGL_CONSTANT GLenum GL_TESS_CONTROL_SHADER = 0x8E88;
CARAVANGL_CONSTANT GLenum GL_COMPUTE_SHADER = 0x91B9;

CARAVANGL_CONSTANT GLenum GL_DELETE_STATUS = 0x8B80;
CARAVANGL_CONSTANT GLenum GL_COMPILE_STATUS = 0x8B81;
CARAVANGL_CONSTANT GLenum GL_LINK_STATUS = 0x8B82;
CARAVANGL_CONSTANT GLenum GL_VALIDATE_STATUS = 0x8B83;
CARAVANGL_CONSTANT GLenum GL_INFO_LOG_LENGTH = 0x8B84;
CARAVANGL_CONSTANT GLenum GL_ATTACHED_SHADERS = 0x8B85;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_UNIFORMS = 0x8B86;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
CARAVANGL_CONSTANT GLenum GL_SHADER_SOURCE_LENGTH = 0x8B88;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_ATTRIBUTES = 0x8B89;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
CARAVANGL_CONSTANT GLenum GL_SHADER_TYPE = 0x8B4F;
CARAVANGL_CONSTANT GLenum GL_CURRENT_PROGRAM = 0x8B8D;

// --- Uniform Types (returned by glGetActiveUniform) ---
CARAVANGL_CONSTANT GLenum GL_FLOAT_VEC2 = 0x8B50;
CARAVANGL_CONSTANT GLenum GL_FLOAT_VEC3 = 0x8B51;
CARAVANGL_CONSTANT GLenum GL_FLOAT_VEC4 = 0x8B52;
CARAVANGL_CONSTANT GLenum GL_DOUBLE_VEC2 = 0x8FFC;
CARAVANGL_CONSTANT GLenum GL_DOUBLE_VEC3 = 0x8FFD;
CARAVANGL_CONSTANT GLenum GL_DOUBLE_VEC4 = 0x8FFE;
CARAVANGL_CONSTANT GLenum GL_INT_VEC2 = 0x8B53;
CARAVANGL_CONSTANT GLenum GL_INT_VEC3 = 0x8B54;
CARAVANGL_CONSTANT GLenum GL_INT_VEC4 = 0x8B55;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_VEC2 = 0x8DC6;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_VEC3 = 0x8DC7;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_VEC4 = 0x8DC8;
CARAVANGL_CONSTANT GLenum GL_BOOL = 0x8B56;
CARAVANGL_CONSTANT GLenum GL_BOOL_VEC2 = 0x8B57;
CARAVANGL_CONSTANT GLenum GL_BOOL_VEC3 = 0x8B58;
CARAVANGL_CONSTANT GLenum GL_BOOL_VEC4 = 0x8B59;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT2 = 0x8B5A;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT3 = 0x8B5B;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT4 = 0x8B5C;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT2x3 = 0x8B65;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT2x4 = 0x8B66;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT3x2 = 0x8B67;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT3x4 = 0x8B68;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT4x2 = 0x8B69;
CARAVANGL_CONSTANT GLenum GL_FLOAT_MAT4x3 = 0x8B6A;
CARAVANGL_CONSTANT GLenum GL_DOUBLE_MAT2 = 0x8F46;
CARAVANGL_CONSTANT GLenum GL_DOUBLE_MAT3 = 0x8F47;
CARAVANGL_CONSTANT GLenum GL_DOUBLE_MAT4 = 0x8F48;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_1D = 0x8B5D;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_2D = 0x8B5E;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_3D = 0x8B5F;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_CUBE = 0x8B60;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_1D_SHADOW = 0x8B61;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_2D_SHADOW = 0x8B62;

// --- Program Interface Query (4.3) ---
CARAVANGL_CONSTANT GLenum GL_UNIFORM = 0x92E1;
CARAVANGL_CONSTANT GLenum GL_UNIFORM_BLOCK = 0x92E2;
CARAVANGL_CONSTANT GLenum GL_PROGRAM_INPUT = 0x92E3;
CARAVANGL_CONSTANT GLenum GL_PROGRAM_OUTPUT = 0x92E4;
CARAVANGL_CONSTANT GLenum GL_BUFFER_VARIABLE = 0x92E5;
CARAVANGL_CONSTANT GLenum GL_SHADER_STORAGE_BLOCK = 0x92E6;
CARAVANGL_CONSTANT GLenum GL_VERTEX_SUBROUTINE = 0x92E8;
CARAVANGL_CONSTANT GLenum GL_TESS_CONTROL_SUBROUTINE = 0x92E9;
CARAVANGL_CONSTANT GLenum GL_TESS_EVALUATION_SUBROUTINE = 0x92EA;
CARAVANGL_CONSTANT GLenum GL_GEOMETRY_SUBROUTINE = 0x92EB;
CARAVANGL_CONSTANT GLenum GL_FRAGMENT_SUBROUTINE = 0x92EC;
CARAVANGL_CONSTANT GLenum GL_COMPUTE_SUBROUTINE = 0x92ED;
CARAVANGL_CONSTANT GLenum GL_VERTEX_SUBROUTINE_UNIFORM = 0x92EE;
CARAVANGL_CONSTANT GLenum GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x92EF;
CARAVANGL_CONSTANT GLenum GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x92F0;
CARAVANGL_CONSTANT GLenum GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x92F1;
CARAVANGL_CONSTANT GLenum GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x92F2;
CARAVANGL_CONSTANT GLenum GL_COMPUTE_SUBROUTINE_UNIFORM = 0x92F3;
CARAVANGL_CONSTANT GLenum GL_TRANSFORM_FEEDBACK_VARYING = 0x92F4;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_RESOURCES = 0x92F5;
CARAVANGL_CONSTANT GLenum GL_MAX_NAME_LENGTH = 0x92F6;
CARAVANGL_CONSTANT GLenum GL_MAX_NUM_ACTIVE_VARIABLES = 0x92F7;
CARAVANGL_CONSTANT GLenum GL_NAME_LENGTH = 0x92F9;
CARAVANGL_CONSTANT GLenum GL_TYPE = 0x92FA;
CARAVANGL_CONSTANT GLenum GL_ARRAY_SIZE = 0x92FB;
CARAVANGL_CONSTANT GLenum GL_OFFSET = 0x92FC;
CARAVANGL_CONSTANT GLenum GL_BLOCK_INDEX = 0x92FD;
CARAVANGL_CONSTANT GLenum GL_ARRAY_STRIDE = 0x92FE;
CARAVANGL_CONSTANT GLenum GL_MATRIX_STRIDE = 0x92FF;
CARAVANGL_CONSTANT GLenum GL_IS_ROW_MAJOR = 0x9300;
CARAVANGL_CONSTANT GLenum GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x9301;
CARAVANGL_CONSTANT GLenum GL_BUFFER_BINDING = 0x9302;
CARAVANGL_CONSTANT GLenum GL_BUFFER_DATA_SIZE = 0x9303;
CARAVANGL_CONSTANT GLenum GL_NUM_ACTIVE_VARIABLES = 0x9304;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_VARIABLES = 0x9305;
CARAVANGL_CONSTANT GLenum GL_REFERENCED_BY_VERTEX_SHADER = 0x9306;
CARAVANGL_CONSTANT GLenum GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x9307;
CARAVANGL_CONSTANT GLenum GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x9308;
CARAVANGL_CONSTANT GLenum GL_REFERENCED_BY_GEOMETRY_SHADER = 0x9309;
CARAVANGL_CONSTANT GLenum GL_REFERENCED_BY_FRAGMENT_SHADER = 0x930A;
CARAVANGL_CONSTANT GLenum GL_REFERENCED_BY_COMPUTE_SHADER = 0x930B;
CARAVANGL_CONSTANT GLenum GL_TOP_LEVEL_ARRAY_SIZE = 0x930C;
CARAVANGL_CONSTANT GLenum GL_TOP_LEVEL_ARRAY_STRIDE = 0x930D;
CARAVANGL_CONSTANT GLenum GL_LOCATION = 0x930E;
CARAVANGL_CONSTANT GLenum GL_LOCATION_INDEX = 0x930F;
CARAVANGL_CONSTANT GLenum GL_IS_PER_PATCH = 0x92E7;

// --- Image Access Qualifiers (4.2) ---
CARAVANGL_CONSTANT GLenum GL_READ_ONLY = 0x88B8;
CARAVANGL_CONSTANT GLenum GL_WRITE_ONLY = 0x88B9;
CARAVANGL_CONSTANT GLenum GL_READ_WRITE = 0x88BA;

// --- Memory Barrier Bits (4.2) ---
CARAVANGL_CONSTANT GLbitfield GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 0x00000001;
CARAVANGL_CONSTANT GLbitfield GL_ELEMENT_ARRAY_BARRIER_BIT = 0x00000002;
CARAVANGL_CONSTANT GLbitfield GL_UNIFORM_BARRIER_BIT = 0x00000004;
CARAVANGL_CONSTANT GLbitfield GL_TEXTURE_FETCH_BARRIER_BIT = 0x00000008;
CARAVANGL_CONSTANT GLbitfield GL_SHADER_IMAGE_ACCESS_BARRIER_BIT = 0x00000020;
CARAVANGL_CONSTANT GLbitfield GL_COMMAND_BARRIER_BIT = 0x00000040;
CARAVANGL_CONSTANT GLbitfield GL_PIXEL_BUFFER_BARRIER_BIT = 0x00000080;
CARAVANGL_CONSTANT GLbitfield GL_TEXTURE_UPDATE_BARRIER_BIT = 0x00000100;
CARAVANGL_CONSTANT GLbitfield GL_BUFFER_UPDATE_BARRIER_BIT = 0x00000200;
CARAVANGL_CONSTANT GLbitfield GL_FRAMEBUFFER_BARRIER_BIT = 0x00000400;
CARAVANGL_CONSTANT GLbitfield GL_TRANSFORM_FEEDBACK_BARRIER_BIT = 0x00000800;
CARAVANGL_CONSTANT GLbitfield GL_ATOMIC_COUNTER_BARRIER_BIT = 0x00001000;
CARAVANGL_CONSTANT GLbitfield GL_SHADER_STORAGE_BARRIER_BIT = 0x00002000;
CARAVANGL_CONSTANT GLbitfield GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT = 0x00004000;
CARAVANGL_CONSTANT GLbitfield GL_QUERY_BUFFER_BARRIER_BIT = 0x00008000;
CARAVANGL_CONSTANT GLbitfield GL_ALL_BARRIER_BITS = 0xFFFFFFFF;

// --- Sync Objects ---
CARAVANGL_CONSTANT GLenum GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001;
CARAVANGL_CONSTANT GLenum GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117;
CARAVANGL_CONSTANT GLenum GL_SYNC_STATUS = 0x9114;
CARAVANGL_CONSTANT GLenum GL_SYNC_CONDITION = 0x9113;
CARAVANGL_CONSTANT GLenum GL_SYNC_FLAGS = 0x9115;
CARAVANGL_CONSTANT GLenum GL_SYNC_FENCE = 0x9116;
CARAVANGL_CONSTANT GLenum GL_OBJECT_TYPE = 0x9112;
CARAVANGL_CONSTANT GLenum GL_ALREADY_SIGNALED = 0x911A;
CARAVANGL_CONSTANT GLenum GL_TIMEOUT_EXPIRED = 0x911B;
CARAVANGL_CONSTANT GLenum GL_CONDITION_SATISFIED = 0x911C;
CARAVANGL_CONSTANT GLenum GL_WAIT_FAILED = 0x911D;
CARAVANGL_CONSTANT GLuint64 GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFFull;

// --- Queries ---
CARAVANGL_CONSTANT GLenum GL_SAMPLES_PASSED = 0x8914;
CARAVANGL_CONSTANT GLenum GL_ANY_SAMPLES_PASSED = 0x8C2F;
CARAVANGL_CONSTANT GLenum GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A;
CARAVANGL_CONSTANT GLenum GL_PRIMITIVES_GENERATED = 0x8C87;
CARAVANGL_CONSTANT GLenum GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88;
CARAVANGL_CONSTANT GLenum GL_TIME_ELAPSED = 0x88BF;
CARAVANGL_CONSTANT GLenum GL_TIMESTAMP = 0x8E28;
CARAVANGL_CONSTANT GLenum GL_QUERY_RESULT = 0x8866;
CARAVANGL_CONSTANT GLenum GL_QUERY_RESULT_AVAILABLE = 0x8867;
CARAVANGL_CONSTANT GLenum GL_QUERY_RESULT_NO_WAIT = 0x9194;

// --- Transform Feedback ---
CARAVANGL_CONSTANT GLenum GL_INTERLEAVED_ATTRIBS = 0x8C8C;
CARAVANGL_CONSTANT GLenum GL_SEPARATE_ATTRIBS = 0x8C8D;
CARAVANGL_CONSTANT GLenum GL_TRANSFORM_FEEDBACK = 0x8E22;

// --- Debug (4.3 KHR_debug) ---
CARAVANGL_CONSTANT GLenum GL_DEBUG_SOURCE_API = 0x8246;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x8247;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SOURCE_SHADER_COMPILER = 0x8248;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SOURCE_THIRD_PARTY = 0x8249;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SOURCE_APPLICATION = 0x824A;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SOURCE_OTHER = 0x824B;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_ERROR = 0x824C;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x824D;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x824E;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_PORTABILITY = 0x824F;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_PERFORMANCE = 0x8250;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_OTHER = 0x8251;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_MARKER = 0x8268;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_PUSH_GROUP = 0x8269;
CARAVANGL_CONSTANT GLenum GL_DEBUG_TYPE_POP_GROUP = 0x826A;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SEVERITY_HIGH = 0x9146;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SEVERITY_MEDIUM = 0x9147;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SEVERITY_LOW = 0x9148;
CARAVANGL_CONSTANT GLenum GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B;
CARAVANGL_CONSTANT GLenum GL_MAX_DEBUG_MESSAGE_LENGTH = 0x9143;
CARAVANGL_CONSTANT GLenum GL_MAX_DEBUG_LOGGED_MESSAGES = 0x9144;
CARAVANGL_CONSTANT GLenum GL_DEBUG_LOGGED_MESSAGES = 0x9145;
CARAVANGL_CONSTANT GLenum GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x8243;
CARAVANGL_CONSTANT GLenum GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x826C;
CARAVANGL_CONSTANT GLenum GL_DEBUG_GROUP_STACK_DEPTH = 0x826D;
CARAVANGL_CONSTANT GLenum GL_MAX_LABEL_LENGTH = 0x82E8;
CARAVANGL_CONSTANT GLenum GL_BUFFER_OBJECT =
    0x9151; // GL_OBJECT_TYPE identifier
CARAVANGL_CONSTANT GLenum GL_SHADER_OBJECT = 0x8B48;
CARAVANGL_CONSTANT GLenum GL_PROGRAM_OBJECT = 0x8B40;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ARRAY_OBJECT = 0x9154;
CARAVANGL_CONSTANT GLenum GL_QUERY_OBJECT = 0x9153;
CARAVANGL_CONSTANT GLenum GL_PROGRAM_PIPELINE_OBJECT = 0x8A4F;
CARAVANGL_CONSTANT GLenum GL_SAMPLER_OBJECT = 0x8C2E; // for object labelling

// --- Vertex Attrib ---
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_ARRAY_LONG = 0x874E;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_BINDING = 0x82D4;
CARAVANGL_CONSTANT GLenum GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5;
CARAVANGL_CONSTANT GLenum GL_VERTEX_BINDING_DIVISOR = 0x82D6;
CARAVANGL_CONSTANT GLenum GL_VERTEX_BINDING_OFFSET = 0x82D7;
CARAVANGL_CONSTANT GLenum GL_VERTEX_BINDING_STRIDE = 0x82D8;
CARAVANGL_CONSTANT GLenum GL_VERTEX_BINDING_BUFFER = 0x8F4F;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_ATTRIB_STRIDE = 0x82E5;

// --- Pixel Store ---
CARAVANGL_CONSTANT GLenum GL_UNPACK_IMAGE_HEIGHT = 0x806E;
CARAVANGL_CONSTANT GLenum GL_UNPACK_SKIP_IMAGES = 0x806D;
CARAVANGL_CONSTANT GLenum GL_PACK_IMAGE_HEIGHT = 0x806C;
CARAVANGL_CONSTANT GLenum GL_PACK_SKIP_IMAGES = 0x806B;

// --- Logic Operations ---
CARAVANGL_CONSTANT GLenum GL_CLEAR = 0x1500;
CARAVANGL_CONSTANT GLenum GL_AND = 0x1501;
CARAVANGL_CONSTANT GLenum GL_AND_REVERSE = 0x1502;
CARAVANGL_CONSTANT GLenum GL_COPY = 0x1503;
CARAVANGL_CONSTANT GLenum GL_AND_INVERTED = 0x1504;
CARAVANGL_CONSTANT GLenum GL_NOOP = 0x1505;
CARAVANGL_CONSTANT GLenum GL_XOR = 0x1506;
CARAVANGL_CONSTANT GLenum GL_OR = 0x1507;
CARAVANGL_CONSTANT GLenum GL_NOR = 0x1508;
CARAVANGL_CONSTANT GLenum GL_EQUIV = 0x1509;
CARAVANGL_CONSTANT GLenum GL_OR_REVERSE = 0x150B;
CARAVANGL_CONSTANT GLenum GL_COPY_INVERTED = 0x150C;
CARAVANGL_CONSTANT GLenum GL_OR_INVERTED = 0x150D;
CARAVANGL_CONSTANT GLenum GL_NAND = 0x150E;
CARAVANGL_CONSTANT GLenum GL_SET = 0x150F;

// --- Provoking Vertex ---
CARAVANGL_CONSTANT GLenum GL_FIRST_VERTEX_CONVENTION = 0x8E4D;
CARAVANGL_CONSTANT GLenum GL_LAST_VERTEX_CONVENTION = 0x8E4E;
CARAVANGL_CONSTANT GLenum GL_PROVOKING_VERTEX = 0x8E4F;

// --- Patch Parameters (Tessellation) ---
CARAVANGL_CONSTANT GLenum GL_PATCH_VERTICES = 0x8E72;
CARAVANGL_CONSTANT GLenum GL_PATCH_DEFAULT_INNER_LEVEL = 0x8E73;
CARAVANGL_CONSTANT GLenum GL_PATCH_DEFAULT_OUTER_LEVEL = 0x8E74;
CARAVANGL_CONSTANT GLenum GL_TESS_GEN_MODE = 0x8E76;
CARAVANGL_CONSTANT GLenum GL_TESS_GEN_SPACING = 0x8E77;
CARAVANGL_CONSTANT GLenum GL_TESS_GEN_VERTEX_ORDER = 0x8E78;
CARAVANGL_CONSTANT GLenum GL_TESS_GEN_POINT_MODE = 0x8E79;

// --- Indirect Draw ---
CARAVANGL_CONSTANT GLenum GL_DRAW_INDIRECT_BUFFER_BINDING = 0x8F43;

// --- Atomic Counters ---
CARAVANGL_CONSTANT GLenum GL_ATOMIC_COUNTER_BUFFER = 0x92C0;
CARAVANGL_CONSTANT GLenum GL_ATOMIC_COUNTER_BUFFER_BINDING = 0x92C1;
CARAVANGL_CONSTANT GLenum GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE = 0x92C4;
CARAVANGL_CONSTANT GLenum GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS =
    0x92C5;
CARAVANGL_CONSTANT GLenum GL_MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2;
CARAVANGL_CONSTANT GLenum GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6;
CARAVANGL_CONSTANT GLenum GL_MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7;
CARAVANGL_CONSTANT GLenum GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x92D8;
CARAVANGL_CONSTANT GLenum GL_ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x92D9;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_ATOMIC_COUNTER = 0x92DB;

// --- Spec-Guaranteed Minimum Implementation Limits ---
// These are compile-time lower bounds from the OpenGL 4.6 specification tables.
// Use glGetIntegerv at runtime to query the actual driver values.
CARAVANGL_CONSTANT GLint GL_MIN_MAP_BUFFER_ALIGNMENT = 64;
CARAVANGL_CONSTANT GLint GL_MIN_PROGRAM_TEXEL_OFFSET = -8;
CARAVANGL_CONSTANT GLint GL_MAX_PROGRAM_TEXEL_OFFSET = 7;
CARAVANGL_CONSTANT GLint GL_SPEC_MIN_UNIFORM_BUFFER_BINDINGS =
    36; // renamed to avoid clash
CARAVANGL_CONSTANT GLint GL_SPEC_MAX_TEXTURE_IMAGE_UNITS = 16;
CARAVANGL_CONSTANT GLint GL_SPEC_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 96;

// --- Misc Sentinel Values ---
CARAVANGL_CONSTANT GLuint GL_INVALID_INDEX = 0xFFFFFFFFu;
CARAVANGL_CONSTANT GLuint GL_INVALID_ENUM_VALUE =
    0xFFFFFFFFu; // returned by GetProgramResourceIndex for not-found
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_BYTE_3_3_2 = 0x8032;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_8_8_8_8 = 0x8035;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_10_10_10_2 = 0x8036;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367;
CARAVANGL_CONSTANT GLenum GL_UNSIGNED_INT_24_8 = 0x84FA;
CARAVANGL_CONSTANT GLenum GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD;

// --- Draw Buffers ---
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER0 = 0x8825;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER1 = 0x8826;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER2 = 0x8827;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER3 = 0x8828;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER4 = 0x8829;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER5 = 0x882A;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER6 = 0x882B;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER7 = 0x882C;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER8 = 0x882D;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER9 = 0x882E;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER10 = 0x882F;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER11 = 0x8830;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER12 = 0x8831;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER13 = 0x8832;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER14 = 0x8833;
CARAVANGL_CONSTANT GLenum GL_DRAW_BUFFER15 = 0x8834;
CARAVANGL_CONSTANT GLenum GL_BACK_LEFT = 0x0402;
CARAVANGL_CONSTANT GLenum GL_BACK_RIGHT = 0x0403;
CARAVANGL_CONSTANT GLenum GL_FRONT_LEFT = 0x0400;
CARAVANGL_CONSTANT GLenum GL_FRONT_RIGHT = 0x0401;
CARAVANGL_CONSTANT GLenum GL_LEFT = 0x0406;
CARAVANGL_CONSTANT GLenum GL_RIGHT = 0x0407;

// -----------------------------------------------------------------------------
// Modern C23 Enums  (unchanged from original)
// -----------------------------------------------------------------------------
typedef enum UniformFunction : uint8_t {
  UF_1I,
  UF_2I,
  UF_3I,
  UF_4I,
  UF_1B,
  UF_2B,
  UF_3B,
  UF_4B,
  UF_1U,
  UF_2U,
  UF_3U,
  UF_4U,
  UF_1F,
  UF_2F,
  UF_3F,
  UF_4F,
  UF_MAT2,
  UF_MAT2x3,
  UF_MAT2x4,
  UF_MAT3x2,
  UF_MAT3,
  UF_MAT3x4,
  UF_MAT4x2,
  UF_MAT4x3,
  UF_MAT4,
  UF_COUNT
} UniformFunction;

typedef enum ImageFormatTupleIndex : uint8_t {
  IF_INTERNAL_FORMAT,
  IF_FORMAT,
  IF_TYPE,
  IF_BUFFER,
  IF_COMPONENTS,
  IF_PIXEL_SIZE,
  IF_COLOR,
  IF_FLAGS,
  IF_CLEAR_TYPE,
  IF_TUPLE_SIZE
} ImageFormatTupleIndex;

#ifndef APIENTRY
  #ifdef _WIN32
    #define APIENTRY __stdcall
  #else
    #define APIENTRY
  #endif
#endif

#ifdef _WIN32
#define GL_API __stdcall
#else
#define GL_API
#endif

typedef void (APIENTRY *GLDEBUGPROC)(
    GLenum source,     // Where the error came from (API, Window System, etc.)
    GLenum type,       // Error, Performance warning, Portability, etc.
    GLuint id,         // Driver-specific ID for this message
    GLenum severity,   // High, Medium, Low, Notification
    GLsizei length,    // Length of the message string
    const GLchar* message, // The actual human-readable string
    const void* userParam  // The pointer you passed in DebugMessageCallback
);

// -----------------------------------------------------------------------------
// OpenGL Single Source of Truth Lists (X-Macros)  (unchanged from original)
// Format: X(Return Type, Function Name, Arguments...)
// -----------------------------------------------------------------------------

// ======================= OPENGL 3.3 CORE =======================
#define GL_FUNCTIONS_3_3_CORE(X)                                               \
  X(void, CullFace, GLenum mode)                                               \
  X(void, Clear, GLbitfield mask)                                              \
  X(void, TexParameteri, GLenum target, GLenum pname, GLint param)             \
  X(void, TexImage2D, GLenum target, GLint level, GLint internalformat,        \
    GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type,   \
    const void *pixels)                                                        \
  X(void, DepthMask, GLboolean flag)                                           \
  X(void, Disable, GLenum cap)                                                 \
  X(void, Enable, GLenum cap)                                                  \
  X(void, Flush, void)                                                         \
  X(void, DepthFunc, GLenum func)                                              \
  X(void, ReadBuffer, GLenum src)                                              \
  X(void, ReadPixels, GLint x, GLint y, GLsizei width, GLsizei height,         \
    GLenum format, GLenum type, void *pixels)                                  \
  X(GLenum, GetError, void)                                                    \
  X(void, GetIntegerv, GLenum pname, GLint *data)                              \
  X(const GLchar *, GetString, GLenum name)                                    \
  X(void, Viewport, GLint x, GLint y, GLsizei width, GLsizei height)           \
  X(void, TexSubImage2D, GLenum target, GLint level, GLint xoffset,            \
    GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type,  \
    const void *pixels)                                                        \
  X(void, BindTexture, GLenum target, GLuint texture)                          \
  X(void, DeleteTextures, GLsizei n, const GLuint *textures)                   \
  X(void, GenTextures, GLsizei n, GLuint *textures)                            \
  X(void, TexImage3D, GLenum target, GLint level, GLint internalformat,        \
    GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, \
    GLenum type, const void *pixels)                                           \
  X(void, TexSubImage3D, GLenum target, GLint level, GLint xoffset,            \
    GLint yoffset, GLint zoffset, GLsizei width, GLsizei height,               \
    GLsizei depth, GLenum format, GLenum type, const void *pixels)             \
  X(void, ActiveTexture, GLenum texture)                                       \
  X(void, BlendFuncSeparate, GLenum sfactorRGB, GLenum dfactorRGB,             \
    GLenum sfactorAlpha, GLenum dfactorAlpha)                                  \
  X(void, BindBuffer, GLenum target, GLuint buffer)                            \
  X(void, DeleteBuffers, GLsizei n, const GLuint *buffers)                     \
  X(void, GenBuffers, GLsizei n, GLuint *buffers)                              \
  X(void, BufferData, GLenum target, GLsizeiptr size, const void *data,        \
    GLenum usage)                                                              \
  X(void, BufferSubData, GLenum target, GLintptr offset, GLsizeiptr size,      \
    const void *data)                                                          \
  X(void, GetBufferSubData, GLenum target, GLintptr offset, GLsizeiptr size,   \
    void *data)                                                                \
  X(void, BlendEquationSeparate, GLenum modeRGB, GLenum modeAlpha)             \
  X(void, DrawBuffers, GLsizei n, const GLenum *bufs)                          \
  X(void, StencilOpSeparate, GLenum face, GLenum sfail, GLenum dpfail,         \
    GLenum dppass)                                                             \
  X(void, StencilFuncSeparate, GLenum face, GLenum func, GLint ref,            \
    GLuint mask)                                                               \
  X(void, StencilMaskSeparate, GLenum face, GLuint mask)                       \
  X(void, AttachShader, GLuint program, GLuint shader)                         \
  X(void, CompileShader, GLuint shader)                                        \
  X(GLuint, CreateProgram, void)                                               \
  X(GLuint, CreateShader, GLenum type)                                         \
  X(void, DeleteProgram, GLuint program)                                       \
  X(void, DeleteShader, GLuint shader)                                         \
  X(void, DetachShader, GLuint program, GLuint shader)                         \
  X(void, DisableVertexAttribArray, GLuint index)                              \
  X(void, EnableVertexAttribArray, GLuint index)                               \
  X(void, GetActiveUniform, GLuint program, GLuint index, GLsizei bufSize,     \
    GLsizei *length, GLint *size, GLenum *type, GLchar *name)                  \
  X(void, GetActiveAttrib, GLuint program, GLuint index, GLsizei bufSize,      \
    GLsizei *length, GLint *size, GLenum *type, GLchar *name)                  \
  X(GLint, GetAttribLocation, GLuint program, const GLchar *name)              \
  X(void, GetProgramiv, GLuint program, GLenum pname, GLint *params)           \
  X(void, GetProgramInfoLog, GLuint program, GLsizei bufSize, GLsizei *length, \
    GLchar *infoLog)                                                           \
  X(void, GetShaderiv, GLuint shader, GLenum pname, GLint *params)             \
  X(void, GetShaderInfoLog, GLuint shader, GLsizei bufSize, GLsizei *length,   \
    GLchar *infoLog)                                                           \
  X(GLint, GetUniformLocation, GLuint program, const GLchar *name)             \
  X(void, LinkProgram, GLuint program)                                         \
  X(void, ShaderSource, GLuint shader, GLsizei count,                          \
    const GLchar *const *string, const GLint *length)                          \
  X(void, UseProgram, GLuint program)                                          \
  X(void, Uniform1i, GLint location, GLint v0)                                 \
  X(void, Uniform1fv, GLint location, GLsizei count, const GLfloat *value)     \
  X(void, Uniform2fv, GLint location, GLsizei count, const GLfloat *value)     \
  X(void, Uniform3fv, GLint location, GLsizei count, const GLfloat *value)     \
  X(void, Uniform4fv, GLint location, GLsizei count, const GLfloat *value)     \
  X(void, Uniform1iv, GLint location, GLsizei count, const GLint *value)       \
  X(void, Uniform2iv, GLint location, GLsizei count, const GLint *value)       \
  X(void, Uniform3iv, GLint location, GLsizei count, const GLint *value)       \
  X(void, Uniform4iv, GLint location, GLsizei count, const GLint *value)       \
  X(void, UniformMatrix2fv, GLint location, GLsizei count,                     \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix3fv, GLint location, GLsizei count,                     \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix4fv, GLint location, GLsizei count,                     \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, Uniform1f, GLint location, GLfloat v0)                               \
  X(void, Uniform1ui, GLint location, GLuint v0)                               \
  X(void, VertexAttribPointer, GLuint index, GLint size, GLenum type,          \
    GLboolean normalized, GLsizei stride, const void *pointer)                 \
  X(void, UniformMatrix2x3fv, GLint location, GLsizei count,                   \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix3x2fv, GLint location, GLsizei count,                   \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix2x4fv, GLint location, GLsizei count,                   \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix4x2fv, GLint location, GLsizei count,                   \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix3x4fv, GLint location, GLsizei count,                   \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, UniformMatrix4x3fv, GLint location, GLsizei count,                   \
    GLboolean transpose, const GLfloat *value)                                 \
  X(void, BindBufferRange, GLenum target, GLuint index, GLuint buffer,         \
    GLintptr offset, GLsizeiptr size)                                          \
  X(void, VertexAttribIPointer, GLuint index, GLint size, GLenum type,         \
    GLsizei stride, const void *pointer)                                       \
  X(void, Uniform1uiv, GLint location, GLsizei count, const GLuint *value)     \
  X(void, Uniform2uiv, GLint location, GLsizei count, const GLuint *value)     \
  X(void, Uniform3uiv, GLint location, GLsizei count, const GLuint *value)     \
  X(void, Uniform4uiv, GLint location, GLsizei count, const GLuint *value)     \
  X(void, ClearBufferiv, GLenum buffer, GLint drawbuffer, const GLint *value)  \
  X(void, ClearBufferuiv, GLenum buffer, GLint drawbuffer,                     \
    const GLuint *value)                                                       \
  X(void, ClearBufferfv, GLenum buffer, GLint drawbuffer,                      \
    const GLfloat *value)                                                      \
  X(void, ClearBufferfi, GLenum buffer, GLint drawbuffer, GLfloat depth,       \
    GLint stencil)                                                             \
  X(void, BindRenderbuffer, GLenum target, GLuint renderbuffer)                \
  X(void, DeleteRenderbuffers, GLsizei n, const GLuint *renderbuffers)         \
  X(void, GenRenderbuffers, GLsizei n, GLuint *renderbuffers)                  \
  X(void, BindFramebuffer, GLenum target, GLuint framebuffer)                  \
  X(void, DeleteFramebuffers, GLsizei n, const GLuint *framebuffers)           \
  X(void, GenFramebuffers, GLsizei n, GLuint *framebuffers)                    \
  X(void, FramebufferTexture2D, GLenum target, GLenum attachment,              \
    GLenum textarget, GLuint texture, GLint level)                             \
  X(void, FramebufferRenderbuffer, GLenum target, GLenum attachment,           \
    GLenum renderbuffertarget, GLuint renderbuffer)                            \
  X(void, GenerateMipmap, GLenum target)                                       \
  X(void, BlitFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, \
    GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask,       \
    GLenum filter)                                                             \
  X(void, RenderbufferStorageMultisample, GLenum target, GLsizei samples,      \
    GLenum internalformat, GLsizei width, GLsizei height)                      \
  X(void, FramebufferTextureLayer, GLenum target, GLenum attachment,           \
    GLuint texture, GLint level, GLint layer)                                  \
  X(void, BindVertexArray, GLuint array)                                       \
  X(void, DeleteVertexArrays, GLsizei n, const GLuint *arrays)                 \
  X(void, GenVertexArrays, GLsizei n, GLuint *arrays)                          \
  X(void, DrawArrays, GLenum mode, GLint first, GLsizei count)                 \
  X(void, DrawElements, GLenum mode, GLsizei count, GLenum type,               \
    const void *indices)                                                       \
  X(void, DrawArraysInstanced, GLenum mode, GLint first, GLsizei count,        \
    GLsizei instancecount)                                                     \
  X(void, DrawElementsInstanced, GLenum mode, GLsizei count, GLenum type,      \
    const void *indices, GLsizei instancecount)                                \
  X(void, DrawRangeElements, GLenum mode, GLuint start, GLuint end,            \
    GLsizei count, GLenum type, const void *indices)                           \
  X(void, CopyBufferSubData, GLenum readTarget, GLenum writeTarget,            \
    GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)                \
  X(GLuint, GetUniformBlockIndex, GLuint program,                              \
    const GLchar *uniformBlockName)                                            \
  X(void, GetActiveUniformBlockiv, GLuint program, GLuint uniformBlockIndex,   \
    GLenum pname, GLint *params)                                               \
  X(void, GetActiveUniformBlockName, GLuint program, GLuint uniformBlockIndex, \
    GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName)                \
  X(void, UniformBlockBinding, GLuint program, GLuint uniformBlockIndex,       \
    GLuint uniformBlockBinding)                                                \
  X(void, GenSamplers, GLsizei count, GLuint *samplers)                        \
  X(void, DeleteSamplers, GLsizei count, const GLuint *samplers)               \
  X(void, BindSampler, GLuint unit, GLuint sampler)                            \
  X(void, SamplerParameteri, GLuint sampler, GLenum pname, GLint param)        \
  X(void, SamplerParameterf, GLuint sampler, GLenum pname, GLfloat param)      \
  X(void, VertexAttribDivisor, GLuint index, GLuint divisor)                   \
  X(void, BindBufferBase, GLenum target, GLuint index, GLuint buffer)          \
  X(void *, MapBufferRange, GLenum target, GLintptr offset, GLsizeiptr length, \
    GLbitfield access)                                                         \
  X(GLboolean, UnmapBuffer, GLenum target)                                     \
  X(void, PixelStorei, GLenum pname, GLint param)                              \
  X(void, GetBufferParameteriv, GLenum target, GLenum pname, GLint *params)    \
  X(GLsync, FenceSync, GLenum condition, GLbitfield flags)                     \
  X(void, DeleteSync, GLsync sync)                                             \
  X(GLenum, ClientWaitSync, GLsync sync, GLbitfield flags, GLuint64 timeout)   \
  X(void, WaitSync, GLsync sync, GLbitfield flags, GLuint64 timeout)           \
  X(void, Finish, void)

// ======================= OPENGL 4.2 CORE =======================
#define GL_FUNCTIONS_4_2_CORE(X)                                               \
  X(void, BindImageTexture, GLuint unit, GLuint texture, GLint level,          \
    GLboolean layered, GLint layer, GLenum access, GLenum format)              \
  X(void, MemoryBarrier, GLbitfield barriers)

// ======================= OPENGL 4.3 CORE =======================
#define GL_FUNCTIONS_4_3_CORE(X)                                               \
  X(void, DispatchCompute, GLuint num_groups_x, GLuint num_groups_y,           \
    GLuint num_groups_z)                                                       \
  X(void, GetProgramInterfaceiv, GLuint program, GLenum programInterface,      \
    GLenum pname, GLint *params)                                               \
  X(void, DebugMessageCallback, GLDEBUGPROC callback, const void *userParam)   \
  X(void, DebugMessageControl, GLenum source, GLenum type, GLenum severity,    \
    GLsizei count, const GLuint *ids, GLboolean enabled)                       \
  X(void, GetProgramResourceiv, GLuint program, GLenum programInterface,       \
    GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize,     \
    GLsizei *length, GLint *params)                                            \
  X(void, GetProgramResourceName, GLuint program, GLenum programInterface,     \
    GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name)

// ======================= OPENGL 4.4 CORE =======================
#define GL_FUNCTIONS_4_4_CORE(X)                                               \
  X(void, BufferStorage, GLenum target, GLsizeiptr size, const void *data,     \
    GLbitfield flags)

// ======================= OPTIONAL / EXPERIMENTAL =======================

// OpenGL 4.3 Core (optional in loader)
#define GL_FUNCTIONS_4_3_OPTIONAL(X)                                           \
  X(void, MultiDrawArraysIndirect, GLenum mode, const void *indirect,          \
    GLsizei drawcount, GLsizei stride)                                         \
  X(void, MultiDrawElementsIndirect, GLenum mode, GLenum type,                 \
    const void *indirect, GLsizei drawcount, GLsizei stride)

// OpenGL 4.6 Core
#define GL_FUNCTIONS_4_6_OPTIONAL(X)                                           \
  X(void, MultiDrawArraysIndirectCount, GLenum mode, const void *indirect,     \
    GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride)                  \
  X(void, MultiDrawElementsIndirectCount, GLenum mode, GLenum type,            \
    const void *indirect, GLintptr drawcount, GLsizei maxdrawcount,            \
    GLsizei stride)

// ARB_bindless_texture
#define GL_FUNCTIONS_EXT_BINDLESS(X)                                           \
  X(GLuint64, GetTextureHandleARB, GLuint texture)                             \
  X(void, MakeTextureHandleResidentARB, GLuint64 handle)                       \
  X(void, MakeTextureHandleNonResidentARB, GLuint64 handle)

// -----------------------------------------------------------------------------
// Type-Safe Generation
// -----------------------------------------------------------------------------

// Master macro for declaring the function pointer type AND the global pointer
// instance. Note: with the gl-prefix-free naming scheme, the loader passes "gl"
// #name to load_opengl_function so the correct symbol ("glDrawArrays" etc.) is
// resolved.
#define DECLARE_GL_FUNC(ret, name, ...)                                        \
  typedef ret(GL_API *PFN##name##PROC)(__VA_ARGS__);                           \
  [[maybe_unused]] static PFN##name##PROC name = nullptr;

// Expand all lists into declarations
GL_FUNCTIONS_3_3_CORE(DECLARE_GL_FUNC)
GL_FUNCTIONS_4_2_CORE(DECLARE_GL_FUNC)
GL_FUNCTIONS_4_3_CORE(DECLARE_GL_FUNC)
GL_FUNCTIONS_4_4_CORE(DECLARE_GL_FUNC)

GL_FUNCTIONS_4_3_OPTIONAL(DECLARE_GL_FUNC)
GL_FUNCTIONS_4_6_OPTIONAL(DECLARE_GL_FUNC)
GL_FUNCTIONS_EXT_BINDLESS(DECLARE_GL_FUNC)